/* GeoOps — POC local. Não contém análise de satélite, IA ou integração GIS reais. */
(() => {'use strict';
const $=id=>document.getElementById(id), $$=q=>[...document.querySelectorAll(q)];
const fmt=n=>n.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TOTAL=1502.42, outer=[[125,242],[245,125],[545,135],[780,128],[955,115],[1218,151],[1306,220],[1293,397],[1350,423],[1382,588],[1358,747],[1268,840],[1140,878],[990,888],[937,914],[704,893],[532,859],[368,909],[184,851],[143,677],[103,545],[119,371]];
const forest=[[240,140],[430,149],[527,163],[551,223],[619,247],[649,154],[766,148],[807,213],[804,289],[842,351],[858,382],[900,407],[954,430],[983,486],[1010,546],[1001,611],[1044,676],[1114,722],[1207,772],[1176,819],[1048,806],[967,847],[942,870],[839,863],[770,846],[704,823],[640,790],[554,754],[474,739],[416,753],[392,819],[341,775],[278,724],[277,677],[223,619],[207,548],[179,482],[183,408],[164,332],[197,288],[202,213]];
const patch=[[549,155],[634,147],[624,230],[562,212]];
const river=[[689,0],[730,70],[770,120],[705,172],[686,213],[710,241],[713,290],[751,328],[786,342],[849,397],[917,416],[950,444],[962,479],[1001,513],[1010,556],[1000,592],[1033,646],[1086,689],[1142,727],[1199,751],[1228,797],[1239,845],[1290,908],[1325,964],[1370,1024]];
const area=points=>Math.abs(points.reduce((n,p,i)=>{let q=points[(i+1)%points.length];return n+p[0]*q[1]-q[0]*p[1]},0)/2);
const extent=area(outer);
const path=points=>'M'+points.map(p=>p.join(',')).join(' L')+' Z';
const riverPath='M'+river.map(p=>p.join(',')).join(' L');
const features=[{id:'native-main',name:'Maciço de vegetação',class:'native',area:area(forest)/extent*TOTAL,path:path(forest)},{id:'open-main',name:'Área aberta principal',class:'open',area:(extent-area(forest)-area(patch))/extent*TOTAL,path:path(outer)+' '+path(forest)+' '+path(patch)},{id:'review-patch',name:'Área de revisão',class:'open',area:area(patch)/extent*TOTAL,path:path(patch)}];
let state={project:'Fazenda Santa Clara',client:'Escritório Ambiental',city:'Município de exemplo',date:'2026-08-15',version:1,processed:true,reviewed:[],mode:'vectors',selected:null,busy:false};
let zoom=1,toastTimer,runToken=0;
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4000)}
function record(title,detail,type='Revisão'){window.GeoBrain?.record({title,detail,type,source:'Estúdio GeoOps · DEMO'})}
function totals(){let native=features.filter(f=>f.class==='native').reduce((n,f)=>n+f.area,0);return{native,open:TOTAL-native}}
function featureMarkup(){return features.map(f=>`<path class="feature${state.selected===f.id?' selected':''}" tabindex="0" role="button" aria-label="Revisar ${esc(f.name)}" data-feature="${f.id}" data-class="${f.class}" d="${f.path}" fill="${f.class==='native'?'#89d59c':'#e6ca74'}" fill-opacity="${Number($('opacity').value)/100}" stroke="${f.class==='native'?'#b9e6bb':'#e7d18b'}" stroke-width="2" fill-rule="evenodd"/>`).join('')}
function draw(){
 $('propertyShape').setAttribute('d',path(outer));$('propertyBoundary').setAttribute('d',path(outer));
 $('vectorGroup').innerHTML=featureMarkup()+`<g data-overlay="app" clip-path="url(#propertyClip)" pointer-events="none"><path d="${riverPath}" fill="none" stroke="#46d8ef" stroke-width="46" opacity=".36"/><path d="${riverPath}" fill="none" stroke="#88eaff" stroke-width="48" stroke-dasharray="5 10" opacity=".38"/></g><g data-overlay="reserve" pointer-events="none"><path d="M240,330 L360,270 L460,280 L610,350 L780,500 L690,700 L400,660 L230,500 Z" fill="#dbc846" fill-opacity=".12" stroke="#f3da69" stroke-width="3"/><path d="M240,330 L360,270 L460,280 L610,350 L780,500 L690,700 L400,660 L230,500 Z" fill="url(#reservePattern)"/><text x="370" y="486" fill="#fff3b0" stroke="#173428" stroke-width=".6" font-size="22" font-weight="600">RL · REFERÊNCIA</text></g><g data-overlay="river" clip-path="url(#propertyClip)" pointer-events="none"><path d="${riverPath}" fill="none" stroke="#163e46" stroke-width="9" opacity=".5"/><path d="${riverPath}" fill="none" stroke="#8ee7ff" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/></g>`;
 syncLayers();syncMetrics();
}
 function syncLayers(){let visible=state.processed&&state.mode!=='image';$('vectorGroup').style.display=visible?'':'none';
 $$('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===state.mode);b.setAttribute('aria-pressed',String(b.dataset.mode===state.mode))});
 $$('[data-layer],#opacity').forEach(el=>el.disabled=state.busy);
 $$('[data-layer]').forEach(el=>{let name=el.dataset.layer;if(name==='boundary')$('propertyBoundary').style.display=el.checked?'':'none';else if(name==='native'||name==='open')$$(`[data-class="${name}"]`).forEach(p=>p.style.display=el.checked?'':'none');else $$(`[data-overlay="${name}"]`).forEach(p=>p.style.display=el.checked?'':'none')});
 $('mapLegend').hidden=!visible;$('mapInstruction').hidden=state.processed||state.busy;$('compareControl').hidden=state.mode!=='compare'||!state.processed;
 $('compareRect').setAttribute('width',state.mode==='compare'?1536*Number($('compareSlider').value)/100:1536);
 $('mapModeLabel').textContent=state.mode==='image'?'IMAGEM ORIGINAL · ILUSTRATIVA':state.mode==='compare'?'COMPARAÇÃO · VETORES À ESQUERDA':'VETORES SUGERIDOS · REVISÃO HUMANA';
 $('layerFeedback').textContent=state.busy?'Aguarde a demonstração de processamento.':state.mode==='image'?'Imagem sem classes. Ao alterar uma camada, os vetores voltam a aparecer.':'Camadas do exemplo ativas. Marque ou desmarque para mostrar e ocultar.';
 const symbols={boundary:['boundary','Limite'],native:['native','Vegetação'],open:['open','Área aberta'],river:['river','Curso d’água'],reserve:['reserve','Reserva Legal'],app:['app','APP']};
 $('mapLegend').innerHTML=$$('[data-layer]:checked').map(el=>`<span><i class="swatch ${symbols[el.dataset.layer][0]}"></i>${symbols[el.dataset.layer][1]}</span>`).join('');
}
function revealForControl(){if(state.busy)return false;let changed=state.mode==='image'||!state.processed;state.processed=true;state.mode='vectors';if(changed)toast('Exemplo vetorizado visível. Você está no modo Vetores.');return true}
function syncMetrics(){let a=totals();['native','open'].forEach(k=>{$(k+'Area').textContent=state.processed?fmt(a[k]):'—';$(k+'Pct').textContent=state.processed?fmt(a[k]/TOTAL*100)+'%':'—'});$('nativeTrack').style.width=(state.processed?a.native/TOTAL*100:50)+'%';$('versionLabel').textContent=`Versão ${String(state.version).padStart(2,'0')} · ${state.reviewed.length?'revisão parcial':'não revisada'}`;$('reviewStatus').textContent=state.reviewed.length?'PARCIAL':'PENDENTE';$('mapStatus').textContent=state.busy?'Processamento visual simulado':state.processed?`${features.length} feições · ${state.reviewed.length} revisada(s) · DEMO`:'Pronto para demonstração'}
function setMode(m){if(state.busy)return;if(m!=='image')state.processed=true;state.mode=m;syncLayers();syncMetrics()}
function officeVisibility(){let frame=$('officeFrame');if(!frame?.getAttribute('src'))return;frame.contentWindow?.postMessage({type:'geoops:office-visibility',visible:$('page-agents').classList.contains('active')&&!document.hidden},location.origin==='null'?'*':location.origin)}
function navigate(name){if(!['mapa','brain','agents','deliver'].includes(name))name='mapa';$$('.page').forEach(p=>p.classList.toggle('active',p.id==='page-'+name));$$('.topbar [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===name));if(name==='deliver')renderSheet();if(name==='agents'&&!$('officeFrame').getAttribute('src'))$('officeFrame').src=$('officeFrame').dataset.src;officeVisibility();history.replaceState(null,'','#'+name);window.dispatchEvent(new CustomEvent('geoops:page',{detail:{name}}));window.GeoBrain?.refresh()}
function info(title,html){$('infoTitle').textContent=title;$('infoBody').innerHTML=html;$('infoDialog').showModal()}
function about(){info('Uma demonstração, com limites claros.',`<p>Esta é uma POC de produto: imagem aérea fictícia gerada por IA, vetores preparados e processamento visual simulado. Nenhuma imagem histórica ou serviço de satélite é consultado.</p><p>Trocar a data altera somente a referência do cenário. Upload registra o nome do arquivo, sem interpretá-lo. A reclassificação e o recálculo proporcional das áreas funcionam localmente.</p><p>O cérebro usa documentos fictícios e respostas pré-definidas com fontes demonstrativas. Os agentes são uma simulação, sem conexão a IA ou ao acervo privado de ninguém.</p><p>Para operação real: perímetro validado, imagem georreferenciada, SRC, método de classificação e revisão por profissional habilitado. APP e Reserva Legal não são reconhecidas juridicamente a partir de pixels.</p>`)}
async function process(){if(state.busy)return;state.busy=true;const token=++runToken;$('processingCard').hidden=false;$('mapViewport').classList.add('processing');$('processMap').disabled=true;$('generateMap').disabled=true;state.mode='vectors';state.processed=false;$('vectorGroup').style.display='none';syncMetrics();syncLayers();
 const steps=[['Perímetro recebido','Cenário demonstrativo carregado; arquivo real não interpretado.'],['Referência da imagem preparada','Base sintética; data selecionada não consulta acervo histórico.'],['Geometria local organizada','Grade gráfica de exemplo. SRC e município reais pendentes.'],['Vegetação sugerida','Polígonos preparados para a demonstração.'],['Áreas abertas e curso d’água sugeridos','Sem delimitação legal automática de APP ou Reserva Legal.'],['Vetores e tabela preparados','Áreas proporcionais à geometria do cenário fictício.'],['Pronto para revisão humana','Clique em uma feição para corrigir sua classificação.']];
 for(let i=0;i<steps.length;i++){if(token!==runToken)return;$('processingTitle').textContent=steps[i][0];$('processingDetail').textContent=steps[i][1];$('processingPercent').textContent=Math.round((i+1)/steps.length*100)+'%';$('processingBar').style.width=(i+1)/steps.length*100+'%';if(i>=3){state.processed=true;draw();if(i===3){$$('[data-class="open"]').forEach(p=>p.style.display='none');$$('[data-overlay="river"]').forEach(p=>p.style.display='none')}}await new Promise(r=>setTimeout(r,650))}
 if(token!==runToken)return;state.busy=false;state.processed=true;$('processingCard').hidden=true;$('mapViewport').classList.remove('processing');$('processMap').disabled=false;$('generateMap').disabled=false;draw();setMode('vectors');record('Vetores sugeridos',`3 feições de exemplo preparadas em ${state.date}. Origem: imagem gerada por IA; nenhum processamento geoespacial real.`,'Processamento');toast('Vetores prontos. Clique no mapa para revisar uma área.');
}
function selectFeature(id){if(!state.processed){toast('Primeiro, clique em Processar imagem.');return}if(state.busy)return;let f=features.find(x=>x.id===id);if(!f)return;state.selected=id;document.querySelector(`[data-layer="${f.class}"]`).checked=true;setMode('vectors');draw();$('reviewIntro').hidden=true;$('reviewForm').hidden=false;$('featureId').textContent='FEIÇÃO '+String(features.indexOf(f)+1).padStart(3,'0');$('featureTitle').textContent=f.name;$('featureArea').textContent=fmt(f.area)+' ha';$('classSelect').value=f.class;$('reviewNote').value=f.note||'';$('classSelect').focus({preventScroll:true})}
function closeReview(){state.selected=null;$('reviewForm').hidden=true;$('reviewIntro').hidden=false;draw()}
function sheetSvg(){let svg=$('mapSvg').cloneNode(true);svg.removeAttribute('id');svg.setAttribute('viewBox','0 0 1536 1024');let group=svg.querySelector('#vectorGroup');group.style.display='';group.removeAttribute('clip-path');svg.querySelectorAll('.feature').forEach(p=>{p.setAttribute('class','');p.removeAttribute('tabindex');p.removeAttribute('role');p.removeAttribute('aria-label')});svg.querySelectorAll('[id]').forEach(p=>{if(p.id!=='propertyClip'&&p.id!=='reservePattern')p.removeAttribute('id')});let html=new XMLSerializer().serializeToString(svg).replace(/propertyClip/g,'sheetPropertyClip').replace(/reservePattern/g,'sheetReservePattern');return html}
function renderSheet(){let a=totals();$('mapSheet').innerHTML=`<header class="sheet-head"><div><span class="sheet-eyebrow">ENGENHARIA AMBIENTAL · CARTOGRAFIA DEMONSTRATIVA</span><h2>Mapa de uso e cobertura do solo</h2><p>${esc(state.project)} · ${esc(state.city)}</p></div><span class="sheet-brand">GeoOps ◈</span></header><div class="sheet-map">${sheetSvg()}<div class="north">N<span>↑</span></div></div><div class="sheet-bottom"><div><h3>LEGENDA</h3><div class="sheet-legend">${$('mapLegend').innerHTML}</div></div><div><h3>QUADRO DE ÁREAS · DEMONSTRAÇÃO</h3><table class="sheet-table"><thead><tr><th>Classe</th><th>Área (ha)</th><th>%</th></tr></thead><tbody><tr><td>Vegetação nativa</td><td>${fmt(a.native)}</td><td>${fmt(a.native/TOTAL*100)}</td></tr><tr><td>Área aberta</td><td>${fmt(a.open)}</td><td>${fmt(a.open/TOTAL*100)}</td></tr><tr><td><strong>Total</strong></td><td><strong>1.502,42</strong></td><td><strong>100,00</strong></td></tr></tbody></table></div></div><div class="sheet-info"><div>REFERÊNCIA DO CENÁRIO<strong>${state.date.split('-').reverse().join('/')}</strong></div><div>VERSÃO / REVISÃO<strong>V${String(state.version).padStart(2,'0')} · ${state.reviewed.length}/3 feições revisadas</strong></div><div>SRC / ESCALA / RT<strong>Não definidos · validação pendente</strong></div></div><div class="sheet-footer">DEMONSTRAÇÃO — IMAGEM GERADA POR IA. SEM VALIDADE TÉCNICA OU GEOGRÁFICA. Áreas fictícias, proporcionais à geometria local. Norte gráfico ilustrativo. Reserva Legal e APP exigem dados e critérios próprios e não integram a soma de cobertura. Responsável técnico: não atribuído.</div>`}
function qa(){let items=[['Camadas obrigatórias','Definir escopo real'],['Sistema de referência (SRC)','Pendente · grade local'],['Geometrias válidas','Validação GIS pendente'],['Duplicidades','Validação GIS pendente'],['Nomenclatura local','IDs únicos no exemplo',true],['Consistência da soma de áreas','1.502,42 ha · 100,00%',true],['Classificação técnica',`${state.reviewed.length}/3 feições revisadas`],['Simbologia e layout','Composição demonstrativa',true],['Arquivos de entrega','SVG/CSV atuais; GIS conceitual']];info('QA técnico — checklist de revisão',`<p>Este checklist distingue o que a interface verifica do que depende de dados geoespaciais reais.</p><table class="qa-table">${items.map(r=>`<tr><td>${r[0]}</td><td class="${r[2]?'pass':''}">${r[1]}</td></tr>`).join('')}</table>`)}
function download(name,data,type){const u=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000)}
async function svgDownload(){try{const original=$('mapSheet').querySelector('svg');let svg=original.cloneNode(true);svg.setAttribute('xmlns','http://www.w3.org/2000/svg');const img=new Image();img.src='assets/aerial-demo-v2.png';await img.decode();const canvas=document.createElement('canvas');canvas.width=1536;canvas.height=1024;canvas.getContext('2d').drawImage(img,0,0);svg.querySelector('image').setAttribute('href',canvas.toDataURL('image/png'));let text=document.createElementNS('http://www.w3.org/2000/svg','text');text.setAttribute('x','24');text.setAttribute('y','995');text.setAttribute('font-size','19');text.setAttribute('fill','#ffffff');text.setAttribute('stroke','#122b20');text.setAttribute('stroke-width','.5');text.textContent='DEMONSTRAÇÃO · BASE SINTÉTICA · SEM VALIDADE GEOGRÁFICA';svg.append(text);download('Mapa_GeoOps_DEMO_v'+state.version+'.svg',new XMLSerializer().serializeToString(svg),'image/svg+xml');toast('Mapa SVG da sessão exportado.')}catch(e){toast('Abra pelo link publicado para exportar o SVG com a imagem incorporada.')}}
// Eventos da interface. Dados digitados são escapados antes de aparecerem em HTML.
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('[data-layer]').forEach(el=>el.onchange=()=>{if(el.dataset.layer!=='boundary')revealForControl();syncLayers();syncMetrics();});
$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){let r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
 $('aboutDemo').onclick=about;$('sourceInfo').onclick=about;$('openQa').onclick=qa;$('processMap').onclick=process;$('reviewDemo').onclick=()=>selectFeature('review-patch');$('cancelReview').onclick=closeReview;
 $('mapSvg').addEventListener('click',e=>{let f=e.target.closest('[data-feature]');if(f)selectFeature(f.dataset.feature)});$('mapSvg').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.dataset.feature){e.preventDefault();selectFeature(e.target.dataset.feature)}});
 $('reviewForm').onsubmit=e=>{e.preventDefault();let f=features.find(x=>x.id===state.selected);if(!f)return;let old=f.class;f.class=$('classSelect').value;document.querySelector(`[data-layer="${f.class}"]`).checked=true;f.note=$('reviewNote').value.slice(0,500);if(!state.reviewed.includes(f.id))state.reviewed.push(f.id);state.version++;record('Classificação revisada',`${f.name}: ${old==='native'?'vegetação nativa':'área aberta'} → ${f.class==='native'?'vegetação nativa':'área aberta'} (${fmt(f.area)} ha). ${f.note}`);closeReview();toast('Classificação salva. Mapa, hectares e percentuais atualizados.');};
 $('opacity').oninput=()=>{if(!revealForControl())return;$('opacityValue').textContent=$('opacity').value+'%';$$('#vectorGroup .feature').forEach(p=>p.setAttribute('fill-opacity',Number($('opacity').value)/100));syncLayers();syncMetrics();};$('compareSlider').oninput=syncLayers;
 function zoomMap(n){zoom=Math.max(1,Math.min(2.4,n));let w=1536/zoom,h=1024/zoom;$('mapSvg').setAttribute('viewBox',`${768-w/2} ${512-h/2} ${w} ${h}`)}$('zoomIn').onclick=()=>zoomMap(zoom+.25);$('zoomOut').onclick=()=>zoomMap(zoom-.25);$('zoomFit').onclick=()=>zoomMap(1);
 $('referenceDate').onchange=()=>{if(!$('referenceDate').value){$('referenceDate').value=state.date;return}state.date=$('referenceDate').value;record('Data de referência alterada',`Cenário em ${state.date}. A base sintética é a mesma; não houve consulta de imagem histórica.`,'Contexto');toast('Data do cenário alterada. A imagem sintética permanece a mesma.')};
 $('newProject').onclick=()=>{$('newDate').value=state.date;$('newDialog').showModal()};$('newProjectForm').onsubmit=e=>{e.preventDefault();if(state.busy){toast('Aguarde o processamento da demonstração.');return}state.project=$('propertyInput').value.trim()||'Propriedade de exemplo';state.client=$('clientInput').value.trim();state.city=$('cityInput').value.trim();state.date=$('newDate').value;state.processed=false;state.mode='image';state.reviewed=[];state.version=1;features[0].class='native';features[1].class='open';features[2].class='open';features.forEach(f=>f.note='');$('projectTitle').textContent=state.project;$('referenceDate').value=state.date;$('perimeterName').textContent=$('perimeterFile').files.length?[...$('perimeterFile').files].map(f=>f.name).join(', '):'santa_clara_demo.geojson';window.GeoBrain?.setProject(state.project+' · DEMO');record('Projeto aberto',`${state.project}. Perímetro: ${$('perimeterName').textContent}. Arquivo não interpretado; cenário ilustrativo.`,'Projeto');$('newDialog').close();closeReview();setMode('image');navigate('mapa');toast('Projeto aberto. O processamento usa o cenário fictício.')};
 $('generateMap').onclick=()=>{if(!state.processed){toast('Processe a imagem e revise as feições antes de gerar o mapa.');return}record('Layout cartográfico gerado',`Mapa versão ${state.version}; quadro de áreas atualizado; ${state.reviewed.length}/3 feições revisadas. Produto demonstrativo.`,'Produto');navigate('deliver')};$('printMap').onclick=()=>{renderSheet();window.print()};$('exportSvg').onclick=svgDownload;
 $('exportCsv').onclick=()=>{let a=totals();download('Quadro_Areas_DEMO_v'+state.version+'.csv','\uFEFFClasse;Area_ha_DEMO;Percentual_DEMO\r\nVegetação nativa;'+fmt(a.native).replace(/\./g,'')+';'+fmt(a.native/TOTAL*100)+'\r\nÁrea aberta;'+fmt(a.open).replace(/\./g,'')+';'+fmt(a.open/TOTAL*100)+'\r\nTotal;1502,42;100,00\r\n','text/csv;charset=utf-8');toast('Tabela atual da sessão exportada.')};
 $('exportSession').onclick=()=>{download('Projeto_GeoOps_DEMO_v'+state.version+'.json',JSON.stringify({notice:'DEMONSTRAÇÃO. Coordenadas gráficas locais, sem SRC; não é GeoJSON nem levantamento real.',project:state,features:features.map(f=>({...f,area_ha_demo:f.area})),total_ha_demo:TOTAL},null,2),'application/json');toast('Sessão exportada em JSON demonstrativo, sem georreferenciamento.')};
 $('reportPreview').onclick=()=>{let a=totals();info('Memorial demonstrativo',`<p><strong>${esc(state.project)}</strong> · ${esc(state.city)}<br>Referência do cenário: ${esc(state.date)} · Versão ${state.version}</p><p>O cenário fictício contém ${fmt(a.native)} ha de vegetação nativa e ${fmt(a.open)} ha de área aberta, somando 1.502,42 ha. Foram revisadas ${state.reviewed.length} de 3 feições na interface.</p><p><strong>Método:</strong> classificação preparada, com revisão manual e áreas proporcionais às geometrias locais. Imagem aérea gerada por IA; não houve análise geoespacial automatizada.</p><p><strong>Pendências:</strong> origem de dados reais, SRC, escala, verificação de campo, QA geoespacial e aprovação do responsável técnico. APP e Reserva Legal não avaliadas.</p><p>Este texto é preenchido por template a partir do estado da sessão, não por IA. Não é laudo nem documento apto a protocolo.</p>`)};
 $('resetDemo').onclick=()=>{if(state.busy){toast('Aguarde o processamento para reiniciar.');return}info('Reiniciar a demonstração?',`<p>As classificações e o histórico fictício desta POC serão limpos. Nenhum arquivo do computador é alterado.</p><button class="btn primary" id="confirmReset">Reiniciar cenário de exemplo</button>`);$('confirmReset').onclick=()=>{try{localStorage.removeItem('geoops-demo-history')}catch(e){}location.href=location.pathname+'#mapa';location.reload()}};
 $('officeFrame').addEventListener('load',officeVisibility);document.addEventListener('visibilitychange',officeVisibility);window.addEventListener('message',e=>{if(e.source!==$('officeFrame').contentWindow||e.origin!==location.origin||e.data?.type!=='geoops:office-event')return;if(typeof e.data.title==='string'&&typeof e.data.detail==='string')record(e.data.title.slice(0,160),e.data.detail.slice(0,1000),'Agentes')});
 window.addEventListener('hashchange',()=>navigate(location.hash.slice(1)));draw();window.GeoBrain?.setProject(state.project+' · DEMO');navigate(location.hash.slice(1)||'mapa');
})();
