/* GeoOps POC demonstrativa. Estado local, sem rede ou IA real. */
(function(){'use strict';
const docs=[
 {id:'d01',title:'Inventário Fazenda Santa Clara — DEMO',file:'01_inventario_santa_clara_demo.csv',type:'Documento',text:'Total demonstrativo de 1.502,42 ha, organizado em 3 feições: nativa principal, aberta principal e área de revisão.',source:'Fonte DEMO: conjunto sintético da POC'},
 {id:'d02',title:'Briefing Fazenda Santa Clara — DEMO',file:'02_briefing_santa_clara_demo.md',type:'Projeto',text:'POC estática para revisão geoespacial fictícia. Não representa uma operação conectada.',source:'Fonte DEMO: cenário sintético'},
 {id:'d03',title:'Imagem de referência — DEMO',file:'03_imagem_ia_santa_clara_demo.png',type:'Imagem',text:'Imagem gerada por IA para referência visual. Não possui resolução, escala ou georreferenciamento.',source:'Fonte DEMO: imagem sintética gerada por IA'},
 {id:'d04',title:'Critérios de classificação — DEMO',file:'04_criterios_classes_demo.pdf',type:'Classificação',text:'Classes locais: vegetação nativa e área aberta. A terceira feição permanece em revisão técnica.',source:'Fonte DEMO: regras sintéticas da POC'},
 {id:'d05',title:'Checklist de validação técnica — DEMO',file:'05_checklist_validacao_demo.md',type:'Revisão',text:'Validar a interpretação das 3 feições e a consistência dos atributos antes da revisão humana.',source:'Fonte DEMO: processo simulado'},
 {id:'d06',title:'Catálogo de produtos — DEMO',file:'06_catalogo_produtos_demo.json',type:'Produtos',text:'Saídas demonstrativas: mapa de revisão, tabela de evidências e parecer humano.',source:'Fonte DEMO: catálogo fictício'},
 {id:'d07',title:'Log de alterações — DEMO',file:'07_alteracoes_demo.log',type:'Revisão',text:'O cenário passou a registrar a área de revisão como pendente de validação técnica.',source:'Fonte DEMO: registro local'},
 {id:'d08',title:'Matriz de origem — DEMO',file:'08_matriz_origem_demo.xlsx',type:'Documento',text:'As três feições foram criadas sinteticamente para esta POC; não há levantamento de campo real.',source:'Fonte DEMO: matriz sintética'},
 {id:'d09',title:'Dicionário de atributos — DEMO',file:'09_dicionario_atributos_demo.md',type:'Classificação',text:'Campos: id_feicao, descricao, classe, origem, revisor e status.',source:'Fonte DEMO: dados sintéticos'},
 {id:'d10',title:'Parecer cartográfico — DEMO',file:'10_parecer_cartografico_demo.md',type:'Produtos',text:'A imagem de IA é apenas ilustração e não sustenta escala, medição ou georreferenciamento.',source:'Fonte DEMO: cartografia fictícia'},
 {id:'d11',title:'Fila de pendências — DEMO',file:'11_pendencias_demo.csv',type:'Revisão',text:'A área de revisão aguarda validação técnica da classe antes de uma decisão humana.',source:'Fonte DEMO: fila local'},
 {id:'d12',title:'Termo de revisão humana — DEMO',file:'12_revisao_humana_demo.md',type:'Projeto',text:'Resultados demonstrativos não são decisão final e exigem revisão humana.',source:'Fonte DEMO: governança simulada'}
];
let project='Projeto GeoOps — DEMO',activeDoc=docs[0],active=false,neuralView=null;
function safeGet(k){try{return localStorage.getItem(k)}catch(_){return null}}function safeSet(k,v){try{localStorage.setItem(k,v);return true}catch(_){return false}}
let history=[];try{history=JSON.parse(safeGet('geoops-demo-history')||'[]')}catch(_){}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function brainMarkup(){return `<div class="brain-shell"><header class="brain-top"><div><div class="brain-kicker">CÉREBRO VIVO · AMBIENTE DEMONSTRATIVO</div><h2>${esc(project)}</h2><p>Relações sintéticas entre artefatos GeoOps. Esta tela não consulta, copia ou treina dados externos.</p></div><span class="brain-local">ESTADO LOCAL · DEMO</span></header><div class="brain-main"><aside class="brain-tree"><h3>Estrutura</h3><button data-folder="all">⌄ Cérebro GeoOps · DEMO</button><button class="brain-indent" data-folder="Projeto">⌄ Projeto</button><button class="brain-indent" data-folder="Imagem">⌄ Imagens</button><button class="brain-indent" data-folder="Classificação">⌄ Classificação</button><button class="brain-indent" data-folder="Revisão">⌄ Revisões</button><button class="brain-indent" data-folder="Produtos">⌄ Produtos</button></aside><main class="brain-stage"><div class="brain-stage-head"><strong>Relações do contexto local</strong><span>WebGL local · arraste para orbitar · selecione um núcleo</span></div><div class="brain-stage-controls"><button type="button" data-neural-zoom="-120" aria-label="Aproximar visualização">＋</button><button type="button" data-neural-zoom="120" aria-label="Afastar visualização">−</button><button type="button" data-neural-reset>Redefinir vista</button></div><div class="brain-neural-list" aria-label="Nós navegáveis">${docs.slice(0,6).map((d,i)=>`<button data-neural-node="${i}" data-doc="${d.id}">${esc(d.type)}</button>`).join('')}</div><p class="brain-webgl-warning" hidden role="status"></p></main><aside class="brain-panel"><h3>Buscar acervo</h3><input class="brain-search" aria-label="Buscar por nome ou arquivo" placeholder="Nome ou arquivo…"><ul class="brain-docs"></ul><div class="brain-detail"></div><div class="brain-quick"><h3>Perguntas rápidas</h3><button data-q="pending">Quais são as pendências?</button><button data-q="origin">Qual a origem das áreas?</button><button data-q="changed">O que mudou?</button><div class="brain-answer" aria-live="polite">Selecione uma pergunta para consultar o estado DEMO.</div></div><div class="brain-history"><h3>Histórico local</h3><ul></ul></div></aside></div></div>`}
function renderDocs(filter='all'){const root=document.querySelector('#brainRoot');if(!root)return;const term=root.querySelector('.brain-search').value.toLowerCase(),list=docs.filter(d=>(filter==='all'||d.type===filter)&&(!term||(d.title+' '+d.file).toLowerCase().includes(term)));root.querySelector('.brain-docs').innerHTML=list.map(d=>`<li class="brain-doc" tabindex="0" data-doc="${d.id}"><strong>${esc(d.title)}</strong><span>${esc(d.file)}</span></li>`).join('')||'<li class="brain-doc">Nenhum documento DEMO encontrado.</li>';root.querySelector('.brain-detail').innerHTML=`<strong>${esc(activeDoc.title)}</strong><br>${esc(activeDoc.text)}<br><em>${esc(activeDoc.source)}</em>`;root.querySelector('.brain-history ul').innerHTML=history.slice(-4).reverse().map(h=>`<li>• ${esc(h.title)}<small>${esc(h.detail||'Evento local sem detalhes.')} · ${esc(h.source||'local')}</small></li>`).join('')||'<li>Sem eventos registrados localmente.</li>';root.querySelectorAll('[data-doc]').forEach(n=>n.classList.toggle('is-selected',n.dataset.doc===activeDoc.id));}
function select(id){activeDoc=docs.find(d=>d.id===id)||activeDoc;renderDocs()}
function answer(q){const last=history[history.length-1],a={pending:'A área de revisão aguarda validação técnica da classe. Evidência: 11_pendencias_demo.csv (DEMO).',origin:'As 3 feições da Fazenda Santa Clara foram criadas sinteticamente para esta POC; não existe levantamento de campo real. Evidência: 08_matriz_origem_demo.xlsx (DEMO).',changed:last?`Último evento local: ${last.detail||last.title}. Evidência: ${last.source||'registro local'} (DEMO).`:'Não há evento local registrado ainda. Referência inicial: 07_alteracoes_demo.log (DEMO).'};document.querySelector('#brainRoot .brain-answer').textContent=a[q]}
async function montarNeural(stage){try{const {NeuralView}=await import('./neural-view.js?v=4');if(!stage.isConnected)return;neuralView=new NeuralView(stage,{onSelect:(i,node)=>{const doc=docs[Math.floor(i/20)]||docs[0];select(doc.id);const status=stage.querySelector('.brain-stage-head span');if(status)status.textContent=`Núcleo selecionado: ${node.rel} · evidência sintética`;}});stage.querySelectorAll('[data-neural-node]').forEach(button=>button.addEventListener('click',()=>neuralView.select(Number(button.dataset.neuralNode)*20)));neuralView.setActive(active);}catch(error){const warning=stage.querySelector('.brain-webgl-warning');warning.hidden=false;warning.textContent='Visualização 3D indisponível: este navegador não iniciou WebGL. O índice documental continua disponível.';console.warn('GeoOps Neural3D não inicializou.',error);}}
function setupBrain(){const root=document.querySelector('#brainRoot');if(!root||root.dataset.ready)return;root.dataset.ready='1';root.innerHTML=brainMarkup();root.addEventListener('click',e=>{const doc=e.target.closest('[data-doc]'),folder=e.target.closest('[data-folder]'),q=e.target.closest('[data-q]');if(doc)select(doc.dataset.doc);if(folder)renderDocs(folder.dataset.folder);if(q)answer(q.dataset.q)});root.addEventListener('keydown',e=>{const doc=e.target.closest('.brain-doc');if(doc&&(e.key==='Enter'||e.key===' ')){e.preventDefault();select(doc.dataset.doc)}});root.querySelector('.brain-search').addEventListener('input',()=>renderDocs());renderDocs();montarNeural(root.querySelector('.brain-stage'));}
function refresh(pageName){setupBrain();active=pageName!==undefined?pageName==='brain':document.querySelector('#page-brain')?.classList.contains('active');neuralView?.setActive(active)}
window.GeoBrain={record(e){if(!e||!e.title)return false;const entry={title:String(e.title),detail:String(e.detail||''),type:String(e.type||'Evento'),source:String(e.source||'local')};history.push(entry);const id='event-'+Date.now();docs.push({id,title:`Memória: ${entry.title} — DEMO`,file:`memoria_local_${id}.md`,type:'Documento',text:entry.detail||'Evento registrado no estado local.',source:`Fonte local DEMO: ${entry.source}`});activeDoc=docs[docs.length-1];safeSet('geoops-demo-history',JSON.stringify(history.slice(-20)));refresh();renderDocs();return true},refresh,setProject(n){if(n)project=String(n);const title=document.querySelector('#brainRoot .brain-top h2');if(title)title.textContent=project;return project}};
window.addEventListener('geoops:page',e=>refresh(e.detail&&e.detail.name));window.addEventListener('resize',()=>{if(active)neuralView?.render(true)});document.addEventListener('DOMContentLoaded',()=>refresh());if(document.readyState!=='loading')refresh();
})();
