/* GeoOps POC demonstrativa. Estado local, sem rede ou IA real. */
(function(){'use strict';
const docs=[
 {id:'d01',title:'Inventário Fazenda Santa Clara — DEMO',file:'01_inventario_santa_clara_demo.csv',type:'Documento',text:'Total demonstrativo de 1.502,42 ha, organizado em 3 feições: nativa principal, aberta principal e área de revisão.',source:'Fonte DEMO: conjunto sintético da POC'},
 {id:'d02',title:'Briefing Fazenda Santa Clara — DEMO',file:'02_briefing_santa_clara_demo.md',type:'Projeto',text:'POC estática para revisão geoespacial fictícia. Não representa uma operação conectada.',source:'Fonte DEMO: cenário sintético'},
 {id:'d03',title:'Imagem de referência — DEMO',file:'03_imagem_ia_santa_clara_demo.png',type:'Imagem',text:'Imagem gerada por IA para referência visual. Não possui resolução, escala ou georreferenciamento.',source:'Fonte DEMO: imagem sintética gerada por IA'},
 {id:'d04',title:'Critérios de classificação — DEMO',file:'04_criterios_classes_demo.pdf',type:'Classificação',text:'Classes locais: vegetação nativa e área aberta. A terceira feição permanece em revisão técnica.',source:'Fonte DEMO: regras sintéticas da POC'},
 {id:'d05',title:'Checklist de validação técnica — DEMO',file:'05_checklist_validacao_demo.md',type:'Revisão',text:'Validar a interpretação das 3 feições e a consistência dos atributos antes da revisão humana.',source:'Fonte DEMO: processo simulado'},
 {id:'d06',title:'Catálogo de produtos — DEMO',file:'06_catalogo_produtos_demo.json',type:'Produtos',text:'Saídas demonstrativas: mapa de revisão, tabela de evidências e parecer humano.',source:'Fonte DEMO: catálogo fictício'},
 {id:'d07',title:'Log de alterações — DEMO',file:'07_alteracoes_demo.log',type:'Revisão',text:'O cenário passou a registrar a área de revisão como pendente de validação técnica.',source:'Fonte DEMO: registro local'},
 {id:'d08',title:'Matriz de origem — DEMO',file:'08_matriz_origem_demo.xlsx',type:'Documento',text:'As três feições foram criadas sinteticamente para a POC; não há levantamento de campo real.',source:'Fonte DEMO: matriz sintética'},
 {id:'d09',title:'Dicionário de atributos — DEMO',file:'09_dicionario_atributos_demo.md',type:'Classificação',text:'Campos: id_feicao, descricao, classe, origem, revisor e status.',source:'Fonte DEMO: dados sintéticos'},
 {id:'d10',title:'Parecer cartográfico — DEMO',file:'10_parecer_cartografico_demo.md',type:'Produtos',text:'A imagem de IA é apenas ilustração e não sustenta escala, medição ou georreferenciamento.',source:'Fonte DEMO: cartografia fictícia'},
 {id:'d11',title:'Fila de pendências — DEMO',file:'11_pendencias_demo.csv',type:'Revisão',text:'A área de revisão aguarda validação técnica da classe antes de uma decisão humana.',source:'Fonte DEMO: fila local'},
 {id:'d12',title:'Termo de revisão humana — DEMO',file:'12_revisao_humana_demo.md',type:'Projeto',text:'Resultados demonstrativos não são decisão final e exigem revisão humana.',source:'Fonte DEMO: governança simulada'}
];
let project='Projeto GeoOps — DEMO', activeDoc=docs[0], active=false, raf=0, canvas, ctx, points=[];
function safeGet(k){try{return localStorage.getItem(k)}catch(e){return null}} function safeSet(k,v){try{localStorage.setItem(k,v);return true}catch(e){return false}}
let history=[];try{history=JSON.parse(safeGet('geoops-demo-history')||'[]')}catch(e){}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function node(t,s){return `<button class="brain-node" data-doc="${s}">${t}<small>DEMO</small></button>`}
function brainMarkup(){return `<div class="brain-shell"><header class="brain-top"><div><div class="brain-kicker">CÉREBRO VIVO · AMBIENTE DEMONSTRATIVO</div><h2>${esc(project)}</h2><p>Índice local de documentos, relações e evidências fictícias. Esta tela não consulta nem treina uma IA.</p></div><span class="brain-local">ESTADO LOCAL · DEMO</span></header><div class="brain-main"><aside class="brain-tree"><h3>Estrutura</h3><button data-folder="all">⌄ Cérebro GeoOps · DEMO</button><button class="brain-indent" data-folder="Projeto">⌄ Projeto</button><button class="brain-indent" data-folder="Imagem">⌄ Imagens</button><button class="brain-indent" data-folder="Classificação">⌄ Classificação</button><button class="brain-indent" data-folder="Revisão">⌄ Revisões</button><button class="brain-indent" data-folder="Produtos">⌄ Produtos</button></aside><main class="brain-stage"><canvas class="brain-network" aria-hidden="true"></canvas><div class="brain-stage-head"><strong>Rede de contexto local</strong><span>Nós clicáveis para explorar os artefatos demonstrativos</span></div><ul class="brain-nodes" aria-label="Nós do cérebro">${node('Projeto','d02')}${node('Documentos','d01')}${node('Imagem','d03')}${node('Classificação','d04')}${node('Revisão','d05')}${node('Produtos','d06')}</ul></main><aside class="brain-panel"><h3>Buscar acervo</h3><input class="brain-search" aria-label="Buscar por nome ou arquivo" placeholder="Nome ou arquivo…"><ul class="brain-docs"></ul><div class="brain-detail"></div><div class="brain-quick"><h3>Perguntas rápidas</h3><button data-q="pending">Quais são as pendências?</button><button data-q="origin">Qual a origem das áreas?</button><button data-q="changed">O que mudou?</button><div class="brain-answer" aria-live="polite">Selecione uma pergunta para consultar o estado DEMO.</div></div><div class="brain-history"><h3>Histórico local</h3><ul></ul></div></aside></div></div>`}
function renderDocs(filter='all'){let root=document.querySelector('#brainRoot');if(!root)return;let term=root.querySelector('.brain-search').value.toLowerCase();let list=docs.filter(d=>(filter==='all'||d.type===filter)&&(!term||(d.title+' '+d.file).toLowerCase().includes(term)));root.querySelector('.brain-docs').innerHTML=list.map(d=>`<li class="brain-doc" tabindex="0" data-doc="${d.id}"><strong>${esc(d.title)}</strong><span>${esc(d.file)}</span></li>`).join('')||'<li class="brain-doc">Nenhum documento DEMO encontrado.</li>';root.querySelector('.brain-detail').innerHTML=`<strong>${esc(activeDoc.title)}</strong><br>${esc(activeDoc.text)}<br><em>${esc(activeDoc.source)}</em>`;root.querySelector('.brain-history ul').innerHTML=history.slice(-4).reverse().map(h=>`<li>• ${esc(h.title)}<small>${esc(h.detail||'Evento local sem detalhes.')} · ${esc(h.source||'local')}</small></li>`).join('')||'<li>Sem eventos registrados localmente.</li>'}
function select(id){activeDoc=docs.find(d=>d.id===id)||activeDoc;document.querySelectorAll('.brain-node').forEach(n=>n.classList.toggle('is-selected',n.dataset.doc===activeDoc.id));renderDocs()}
function answer(q){const last=history[history.length-1];const a={pending:'A área de revisão aguarda validação técnica da classe. Evidência: 11_pendencias_demo.csv (DEMO).',origin:'As 3 feições da Fazenda Santa Clara foram criadas sinteticamente para esta POC; não existe levantamento de campo real. Evidência: 08_matriz_origem_demo.xlsx (DEMO).',changed:last?`Último evento local: ${last.detail||last.title}. Evidência: ${last.source||'registro local'} (DEMO).`:'Não há evento local registrado ainda. Referência inicial: 07_alteracoes_demo.log (DEMO).'};document.querySelector('#brainRoot .brain-answer').textContent=a[q]}
function setupBrain(){let root=document.querySelector('#brainRoot');if(!root||root.dataset.ready)return;root.dataset.ready='1';root.innerHTML=brainMarkup();canvas=root.querySelector('canvas');ctx=canvas.getContext('2d');root.addEventListener('click',e=>{let d=e.target.closest('[data-doc]'),f=e.target.closest('[data-folder]'),q=e.target.closest('[data-q]');if(d)select(d.dataset.doc);if(f)renderDocs(f.dataset.folder);if(q)answer(q.dataset.q)});root.addEventListener('keydown',e=>{let d=e.target.closest('.brain-doc');if(d&&(e.key==='Enter'||e.key===' ')){e.preventDefault();select(d.dataset.doc)}});root.querySelector('.brain-search').addEventListener('input',()=>renderDocs());renderDocs();resize();}
function resize(){if(!canvas)return;let r=canvas.getBoundingClientRect(),ratio=devicePixelRatio||1;if(!r.width||!r.height)return;canvas.width=r.width*ratio;canvas.height=r.height*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);points=Array.from({length:156},()=>{let a=Math.random()*Math.PI*2,b=Math.acos(2*Math.random()-1),rad=Math.pow(Math.random(),.55);return{x:Math.cos(a)*Math.sin(b)*rad,y:Math.sin(a)*Math.sin(b)*rad,z:Math.cos(b)*rad,phase:Math.random()*6.28}})}
function draw(){if(!active)return;let r=canvas.getBoundingClientRect(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(!r.width||!points.length){resize();if(!points.length)return}ctx.clearRect(0,0,r.width,r.height);let t=Date.now()/5000,project=p=>{let ang=t*.32,xx=p.x*Math.cos(ang)-p.z*Math.sin(ang),zz=p.x*Math.sin(ang)+p.z*Math.cos(ang),scale=1/(1.35-zz*.35);return{x:r.width*.5+xx*r.width*.34*scale,y:r.height*.55+p.y*r.height*.31*scale,z:zz}};let view=points.map(project);for(let i=0;i<view.length;i++)for(let j=i+1;j<view.length;j++){let a=view[i],b=view[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<72&&Math.abs(a.z-b.z)<.45){ctx.strokeStyle=`rgba(66,194,224,${.16*(1-d/72)})`;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}view.forEach((p,i)=>{ctx.fillStyle=`rgba(151,231,245,${.28+(p.z+1)*.2})`;ctx.beginPath();ctx.arc(p.x,p.y,1.1+(p.z+1)*.9,0,7);ctx.fill()});if(!reduced)raf=requestAnimationFrame(draw);else raf=0}
const agents=[['Imagem','Imagem de IA · DEMO','Confere a referência visual sintética, sem resolução, escala ou georreferenciamento.','03_imagem_ia_santa_clara_demo.png'],['Vetorização','3 feições DEMO','Organiza as feições sintéticas e seus atributos simulados.','01_inventario_santa_clara_demo.csv'],['QA','Validação técnica DEMO','Confere campos obrigatórios e mantém a área de revisão pendente.','05_checklist_validacao_demo.md'],['Cartografia','Produto DEMO','Prepara uma composição ilustrativa sem escala operacional.','10_parecer_cartografico_demo.md'],['Memória','Registro local','Guarda evidências no histórico desta sessão local.','07_alteracoes_demo.log']];
function agentsMarkup(){return `<div class="agent-shell"><header class="agent-top"><div><div class="agent-kicker">EQUIPE DE AGENTES · SIMULAÇÃO LOCAL</div><h2>Fluxo assistido com evidências DEMO</h2><p>Execução visual sequencial. Os cards não se conectam a sistemas externos e não substituem a revisão humana.</p></div><span class="brain-local">SIMULAÇÃO · DEMO</span></header><div class="agent-grid">${agents.map((a,i)=>`<article class="agent-card" data-state="idle"><div class="agent-badge">0${i+1} · ${a[1]}</div><h3>${a[0]}</h3><p>${a[2]}</p><div class="agent-state"><i class="agent-dot"></i><span>Aguardando simulação</span></div><div class="agent-evidence">Evidência esperada: <strong>${a[3]}</strong></div></article>`).join('')}</div><div class="agent-controls"><button class="agent-run">Executar simulação DEMO</button><span class="agent-status" aria-live="polite">Pronta para uma execução local.</span></div><footer class="agent-foot"><span class="agent-requirement">Etapa obrigatória:</span> terminar em revisão humana; nenhum resultado DEMO é uma decisão operacional.</footer></div>`}
function setupAgents(){let root=document.querySelector('#agentsRoot');if(!root||root.dataset.ready)return;root.dataset.ready='1';root.innerHTML=agentsMarkup();let btn=root.querySelector('.agent-run');btn.onclick=async()=>{btn.disabled=true;let cards=[...root.querySelectorAll('.agent-card')],status=root.querySelector('.agent-status');for(let i=0;i<cards.length;i++){let card=cards[i],state=card.querySelector('.agent-state span');card.dataset.state='working';state.textContent='Processando evidência DEMO…';status.textContent=`Etapa ${i+1}/5: ${agents[i][0]} em simulação.`;await new Promise(r=>setTimeout(r,600));card.dataset.state='done';state.textContent='Evidência DEMO registrada';history.push({title:`${agents[i][0]} concluiu simulação`,source:agents[i][3]})}safeSet('geoops-demo-history',JSON.stringify(history.slice(-20)));status.textContent='Simulação encerrada: encaminhada para revisão humana.';btn.textContent='Simulação concluída';if(document.querySelector('#brainRoot'))renderDocs()}}
function refresh(pageName){setupBrain();setupAgents();if(pageName!==undefined)active=pageName==='brain';else{let brainPage=document.querySelector('#page-brain');active=!!brainPage&&brainPage.classList.contains('active')}if(active){resize();if(!raf)draw()}if(!active&&raf){cancelAnimationFrame(raf);raf=0}}
window.GeoBrain={record(e){if(!e||!e.title)return false;let entry={title:String(e.title),detail:String(e.detail||''),type:String(e.type||'Evento'),source:String(e.source||'local')};history.push(entry);let id='event-'+Date.now();docs.push({id,title:`Memória: ${entry.title} — DEMO`,file:`memoria_local_${id}.md`,type:'Documento',text:entry.detail||'Evento registrado no estado local.',source:`Fonte local DEMO: ${entry.source}`});activeDoc=docs[docs.length-1];safeSet('geoops-demo-history',JSON.stringify(history.slice(-20)));refresh();if(document.querySelector('#brainRoot'))renderDocs();return true},refresh,setProject(n){if(n)project=String(n);let title=document.querySelector('#brainRoot .brain-top h2');if(title)title.textContent=project;return project}};
window.addEventListener('geoops:page',e=>refresh(e.detail&&e.detail.name));window.addEventListener('resize',()=>{if(active){resize();if(!raf)draw()}});document.addEventListener('DOMContentLoaded',()=>refresh());if(document.readyState!=='loading')refresh();
})();
