/* Public, reproducible PyQGIS study result. Source-specific candidates, not legal findings. */
((root) => {'use strict';
const ORDER=['AREA_CONSOLIDADA','ARL','AVN-DESC-APP','APP','RIO_ATE_10'];
const DRAW_ORDER=['AREA_CONSOLIDADA','AVN-DESC-APP','APP','ARL','RIO_ATE_10'];
const TYPES={
 AREA_CONSOLIDADA:{title:'AC · uso persistente',color:'#e8c651',fill:'url(#geoops-auto-ac)',opacity:.72,legend:'agro-hatch'},
 ARL:{title:'ARL · proposta',color:'#e8a33a',fill:'#e8a33a',opacity:0,dashArray:'9 6',legend:'reserve-dash'},
 'AVN-DESC-APP':{title:'AVN–DESC–APP',color:'#2db763',fill:'url(#geoops-auto-native)',opacity:.82,legend:'native-dots'},
 APP:{title:'APP · faixa de análise',color:'#50a6d2',fill:'url(#geoops-auto-app)',opacity:.86,legend:'app-hatch'},
 RIO_ATE_10:{title:'RIO_ATE_10 · largura não verificada',color:'#138ac4',opacity:0,legend:'river-line'}
};
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=2)=>Number(n).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
function init({map,toast,bringBoundary,hideCoverage,hideManual}){
 const panel=document.createElement('section');panel.className='auto-workspace';panel.id='autoWorkspace';panel.setAttribute('aria-label','Análise automática do caso público');
 panel.innerHTML='<div class="section-title"><h2>Análise automática</h2><span id="autoBadge">ESTUDO</span></div><p class="subtle">Botucatu/SP · vetores calculados no PyQGIS a partir de dados públicos. As cinco camadas abaixo são <b>candidatas para revisão</b>, não aprovação ambiental.</p><div class="auto-actions"><button id="autoShow" class="button primary" type="button">Mostrar análise no mapa</button><button id="autoImage" class="button" type="button">Só imagem</button></div><div id="autoRows" class="auto-rows"><p class="subtle">Carregando camadas de estudo…</p></div><div id="autoSelected" class="auto-selected" hidden><strong id="autoSelectedTitle"></strong><span id="autoSelectedSource"></span><p id="autoSelectedWarning"></p></div><div id="autoOther" class="auto-other"></div><p class="subtle auto-footnote">APP: corredor geométrico a partir do eixo do rio; ARL: proposta ilustrativa, não CAR. “Área consolidada” é indício por comparação de 2008/2023, sem prova do marco legal. As áreas se sobrepõem e não devem ser somadas.</p><a class="button full auto-download" href="public-data/analise-automatica.json" download="GeoOps_analise_automatica_CANDIDATOS.geojson">Baixar vetores de estudo · GeoJSON</a>';
 document.getElementById('manualWorkspace').before(panel);
 const legend=document.createElement('div');legend.className='auto-legend';legend.id='autoLegend';document.getElementById('manualLegend').before(legend);
 const presentation=document.createElement('div');presentation.className='presentation-auto';presentation.id='presentationAuto';presentation.hidden=true;document.getElementById('presentationManual').before(presentation);
 let data=null,active=false,selected=null;const layers=new Map(),visible=new Set(ORDER);
 function patterns(){const svg=document.querySelector('#gisMap .leaflet-overlay-pane svg');if(!svg||svg.querySelector('#geoops-auto-patterns'))return;const defs=document.createElementNS('http://www.w3.org/2000/svg','defs');defs.id='geoops-auto-patterns';defs.innerHTML='<pattern id="geoops-auto-ac" patternUnits="userSpaceOnUse" width="8" height="8" patternTransform="rotate(35)"><path d="M0 0V8" stroke="#f3d95c" stroke-width="2"/></pattern><pattern id="geoops-auto-native" patternUnits="userSpaceOnUse" width="8" height="8"><circle cx="4" cy="4" r="1.7" fill="#56d36d"/></pattern><pattern id="geoops-auto-app" patternUnits="userSpaceOnUse" width="8" height="8" patternTransform="rotate(35)"><path d="M0 0V8" stroke="#6cc7e5" stroke-width="2"/></pattern>';svg.prepend(defs)}
 function metric(code){const m=data?.metadata?.summary?.[code];return m?.areaHa!=null?`${fmt(m.areaHa)} ha`:m?.lengthKm!=null?`${fmt(m.lengthKm,3)} km`:'—'}
 function render(){if(!data)return;panel.classList.toggle('inactive',!active);document.body.classList.toggle('auto-active',active);document.getElementById('mapLegend').classList.toggle('auto-mode',active);document.getElementById('mapLegend').querySelector('strong').textContent=active?'Análise automática · candidatos':'Traçados deste exemplo';document.getElementById('viewImage').classList.toggle('active',!active&&!document.getElementById('showPolygons').checked);document.getElementById('viewVectors').classList.toggle('active',active||document.getElementById('showPolygons').checked);
  document.getElementById('autoBadge').textContent=active?'5 CAMADAS':'PRONTO';document.getElementById('autoRows').innerHTML=ORDER.map(code=>{const type=TYPES[code],m=data.metadata.summary[code];return `<button type="button" class="auto-row${visible.has(code)&&active?' on':''}" data-auto-code="${code}" aria-pressed="${active&&visible.has(code)}"><i class="legend-${code==='RIO_ATE_10'?'line':'fill'} ${type.legend}"></i><span><b>${escapeHtml(type.title)}</b><small>${escapeHtml(m.source)}</small></span><strong>${metric(code)}</strong></button>`}).join('');
  legend.innerHTML=active?ORDER.filter(code=>visible.has(code)).map(code=>`<div><i class="legend-${code==='RIO_ATE_10'?'line':'fill'} ${TYPES[code].legend}"></i><span>${escapeHtml(TYPES[code].title)}</span></div>`).join(''):'';
  document.getElementById('autoOther').innerHTML='<b>Outros itens do quadro</b>'+[['CERRADO_2023','Cerrado mapeado'],['FLORESTA_2023','Floresta mapeada'],['AUAS','AUAS'],['UT_PUBLICA','Utilidade pública']].map(([code,label])=>`<span>${label}<strong>${data.metadata.summary[code]?.areaHa!=null?`${fmt(data.metadata.summary[code].areaHa)} ha`:'não avaliado'}</strong></span>`).join('')+'<small>Classes de cobertura ≠ definição jurídica. Itens não avaliados não são zero.</small>';
  presentation.hidden=!active;presentation.innerHTML=active?'<b>ANÁLISE AUTOMÁTICA · CANDIDATOS</b>'+ORDER.map(code=>`<span>${escapeHtml(TYPES[code].title)} <strong>${metric(code)}</strong></span>`).join('')+'<small>Sobreposições não somadas · validação pendente</small>':'';
  document.getElementById('autoSelected').hidden=!selected||!active;if(selected&&active){const m=data.metadata.summary[selected];document.getElementById('autoSelectedTitle').textContent=`${TYPES[selected].title} · ${metric(selected)}`;document.getElementById('autoSelectedSource').textContent=`Fonte: ${m.source}`;document.getElementById('autoSelectedWarning').textContent=m.warning}
  for(const code of DRAW_ORDER){const layer=layers.get(code);if(!layer)continue;if(active&&visible.has(code)){if(!map.hasLayer(layer))layer.addTo(map);layer.eachLayer(shape=>shape.bringToFront())}else if(map.hasLayer(layer))map.removeLayer(layer)}patterns();bringBoundary();
  document.querySelectorAll('.target-grid>div').forEach(card=>{const code=card.querySelector('strong')?.textContent?.trim(),status=card.querySelector('em');if(!status||!code||!TYPES[code])return;status.textContent=active?'Candidato · revisar':status.dataset.original||'Pendente'});
  const target=document.querySelector('.target-scope');if(target&&active){target.querySelector('h2').textContent='Camadas calculadas para estudo · validação pendente.';target.querySelector('p').textContent='Resultado espacial reproduzível com MapBiomas 2008/2023 e Rio Pardo no OpenStreetMap. APP, ARL, RIO_ATE_10 e área consolidada não foram juridicamente confirmados; veja a origem e a ressalva de cada camada.'}
 }
 async function load(){if(data)return data;const response=await fetch('public-data/analise-automatica.json?v=15',{cache:'no-store'});if(!response.ok)throw Error('As camadas automáticas do exemplo não foram encontradas.');const payload=await response.json();if(payload?.features?.length!==5||!payload.metadata?.summary)throw Error('Arquivo de análise inválido.');data=payload;
  for(const code of ORDER){const feature=data.features.find(f=>f.properties?.code===code);if(!feature)throw Error(`Falta a camada ${code}.`);const type=TYPES[code],isRiver=code==='RIO_ATE_10';const layer=L.geoJSON(feature,{style:{color:type.color,weight:isRiver?4:code==='ARL'?2.8:1.8,dashArray:type.dashArray||null,opacity:1,fillColor:type.fill||type.color,fillOpacity:type.opacity,interactive:true},onEachFeature:(_,shape)=>{shape.bindTooltip(`${escapeHtml(type.title)} · ${metric(code)}`,{sticky:true});shape.on('click',event=>{L.DomEvent.stopPropagation(event);selected=code;render();panel.scrollIntoView({block:'nearest',behavior:'smooth'})})}});layers.set(code,layer)}render();return data}
 async function show(){await load();hideCoverage();active=true;render();toast('Cinco camadas de estudo exibidas. Clique em cada uma para ver fonte e ressalva.');return data}
 function hide(){active=false;selected=null;render()}
 panel.querySelector('#autoShow').onclick=()=>show().catch(e=>toast(e.message));panel.querySelector('#autoImage').onclick=()=>{hide();hideCoverage();hideManual?.()};
 panel.querySelector('#autoRows').onclick=event=>{const code=event.target.closest('[data-auto-code]')?.dataset.autoCode;if(!code||!data)return;if(visible.has(code))visible.delete(code);else visible.add(code);hideCoverage();active=true;selected=code;render()};
 return{load,show,hide,bringToFront:()=>{for(const code of DRAW_ORDER)layers.get(code)?.eachLayer(layer=>layer.bringToFront());bringBoundary()},get active(){return active},get ready(){return Boolean(data)},get data(){return data}}
}
root.GeoOpsAuto={init,TYPES};
})(globalThis);
