/* Human-drawn technical vectors. Browser measurements are estimates, never legal delineations. */
((root)=>{'use strict';
const EARTH_RADIUS=6378137;
const TYPES={
 APP:{label:'APP',geometry:'Polygon',color:'#3988bc',fill:'url(#geoops-manual-app)',legend:'app-hatch'},
 ARL:{label:'ARL',geometry:'Polygon',color:'#e1a13a',fill:'#edae55',legend:'reserve-dash',dashArray:'9 6'},
 'AVN-DESC-APP':{label:'AVN-DESC-APP',geometry:'Polygon',color:'#2c9652',fill:'url(#geoops-manual-native)',legend:'native-dots'},
 AREA_CONSOLIDADA:{label:'ÁREA CONSOLIDADA',geometry:'Polygon',color:'#d5b341',fill:'url(#geoops-manual-consolidated)',legend:'agro-hatch'},
 RIO_ATE_10:{label:'RIO_ATE_10',geometry:'LineString',color:'#2381bd',legend:'river-line'}
};
const rad=n=>n*Math.PI/180;
function ringArea(ring){let sum=0;for(let i=0;i<ring.length-1;i++){const a=ring[i],b=ring[i+1];sum+=rad(b[0]-a[0])*(2+Math.sin(rad(a[1]))+Math.sin(rad(b[1])))}return Math.abs(sum*EARTH_RADIUS*EARTH_RADIUS/2)}
function distance(a,b){const dLat=rad(b[1]-a[1]),dLon=rad(b[0]-a[0]);const h=Math.sin(dLat/2)**2+Math.cos(rad(a[1]))*Math.cos(rad(b[1]))*Math.sin(dLon/2)**2;return 2*EARTH_RADIUS*Math.asin(Math.min(1,Math.sqrt(h)))}
function measure(geometry){if(geometry?.type==='Polygon'){const rings=geometry.coordinates||[];return{areaHa:Math.max(0,(ringArea(rings[0]||[])-rings.slice(1).reduce((n,r)=>n+ringArea(r),0))/10000),lengthKm:0}}if(geometry?.type==='LineString'){const points=geometry.coordinates||[];let metres=0;for(let i=0;i<points.length-1;i++)metres+=distance(points[i],points[i+1]);return{areaHa:0,lengthKm:metres/1000}}return{areaHa:0,lengthKm:0}}
function isValidEntry(entry){if(!entry||!TYPES[entry.role]||typeof entry.id!=='string'||entry.id.length>90||typeof entry.name!=='string'||entry.name.length>100)return false;const geometry=entry.geometry;if(geometry?.type!==TYPES[entry.role].geometry)return false;const points=geometry.type==='Polygon'?geometry.coordinates?.flat(1):geometry.coordinates;if(!Array.isArray(points)||points.length<2||points.length>3000)return false;return points.every(p=>Array.isArray(p)&&p.length>=2&&Number.isFinite(p[0])&&Number.isFinite(p[1])&&Math.abs(p[0])<=180&&Math.abs(p[1])<=90)}
function init({map,toast,showMap}){
 const $=id=>document.getElementById(id),fmt=(n,d=2)=>Number(n).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d}),esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 const group=L.featureGroup().addTo(map),layers=new Map();let entries=[],selectedId=null,handler=null,activeRole=null,editingLayer=null,storageKey=null,contextId=null,hasCoverage=false,ready=false;
 function save(){if(!storageKey)return;try{localStorage.setItem(storageKey,JSON.stringify(entries))}catch{toast('O navegador não conseguiu guardar os traçados. Baixe o GeoJSON antes de sair.')}}
 function load(){if(!storageKey)return[];try{const value=JSON.parse(localStorage.getItem(storageKey)||'[]');return Array.isArray(value)?value.filter(isValidEntry).slice(0,100):[]}catch{return[]}}
 function metricText(entry){const m=measure(entry.geometry);return TYPES[entry.role].geometry==='LineString'?`${fmt(m.lengthKm,3)} km`:`${fmt(m.areaHa,4)} ha`}
 function vectorStyle(entry){const type=TYPES[entry.role],chosen=entry.id===selectedId;return{color:type.color,weight:chosen?4:type.geometry==='LineString'?3:2.5,dashArray:type.dashArray||null,fillColor:type.fill||type.color,fillOpacity:type.geometry==='LineString'?0:entry.role==='ARL'?.09:.62,opacity:1}}
 function patterns(){const svg=$('gisMap').querySelector('.leaflet-overlay-pane svg');if(!svg||svg.querySelector('#geoops-manual-patterns'))return;const defs=document.createElementNS('http://www.w3.org/2000/svg','defs');defs.id='geoops-manual-patterns';defs.innerHTML='<pattern id="geoops-manual-app" patternUnits="userSpaceOnUse" width="8" height="8" patternTransform="rotate(35)"><path d="M0 0V8" stroke="#4c9ac4" stroke-width="2"/></pattern><pattern id="geoops-manual-native" patternUnits="userSpaceOnUse" width="8" height="8"><circle cx="4" cy="4" r="1.6" fill="#42b965"/></pattern><pattern id="geoops-manual-consolidated" patternUnits="userSpaceOnUse" width="8" height="8" patternTransform="rotate(35)"><path d="M0 0V8" stroke="#e6c948" stroke-width="2"/></pattern>';svg.prepend(defs)}
 function render(){group.clearLayers();layers.clear();for(const entry of entries){const shape=L.geoJSON({type:'Feature',geometry:entry.geometry,properties:{}},{style:()=>vectorStyle(entry)});shape.eachLayer(layer=>{layer.bindTooltip(`${esc(entry.name)} · ${metricText(entry)}`,{sticky:true});layer.on('click',()=>select(entry.id));group.addLayer(layer);layers.set(entry.id,layer)})}if($('manualVisible').checked&&!map.hasLayer(group))group.addTo(map);if(!$('manualVisible').checked&&map.hasLayer(group))map.removeLayer(group);patterns();
 $('manualCount').textContent=`${entries.length} ${entries.length===1?'vetor':'vetores'}`;$('manualDownload').disabled=!entries.length;$('manualList').innerHTML=entries.length?entries.map(entry=>`<button class="manual-item${entry.id===selectedId?' selected':''}" type="button" data-manual-id="${esc(entry.id)}"><i class="legend-${TYPES[entry.role].geometry==='LineString'?'line':'fill'} ${TYPES[entry.role].legend}"></i><span>${esc(entry.name)}<small>${metricText(entry)} · rascunho</small></span></button>`).join(''):'<p class="subtle">Nenhum traçado criado ainda.</p>';
 const selected=entries.find(e=>e.id===selectedId);$('manualSelection').hidden=!selected;if(selected){$('manualSelectedName').textContent=selected.name;$('manualSelectedMetric').textContent=metricText(selected)}
 const grouped=new Map();for(const entry of entries){const m=measure(entry.geometry);const prior=grouped.get(entry.role)||{areaHa:0,lengthKm:0};prior.areaHa+=m.areaHa;prior.lengthKm+=m.lengthKm;grouped.set(entry.role,prior)}$('presentationManual').hidden=!entries.length;$('presentationManual').innerHTML=entries.length?'<b>TRAÇADOS MANUAIS · ESTIMATIVA</b>'+[...grouped].map(([role,m])=>`<span>${esc(TYPES[role].label)} <strong>${TYPES[role].geometry==='LineString'?fmt(m.lengthKm,3)+' km':fmt(m.areaHa)+' ha'}</strong></span>`).join(''):'';
 $('manualLegend').innerHTML=[...grouped.keys()].map(role=>`<div><i class="legend-${TYPES[role].geometry==='LineString'?'line':'fill'} ${TYPES[role].legend}"></i><span>${esc(TYPES[role].label)} · rascunho</span></div>`).join('');$('mapLegend').hidden=!(hasCoverage||entries.length||document.body.classList.contains('auto-active'));$('mapLegend').classList.toggle('manual-only',!hasCoverage);if(!document.body.classList.contains('auto-active'))$('mapLegend').querySelector(':scope > strong').textContent=hasCoverage?'Traçados deste exemplo':'Traçados manuais · rascunho';$('mapLegendDetails').textContent=entries.length?'Traçados manuais · revisar ↗':'APP · ARL · AC: ainda sem vetores ↗';
 const autoActive=document.body.classList.contains('auto-active');document.querySelectorAll('.target-grid>div').forEach(card=>{const role=card.querySelector('strong')?.textContent?.trim(),status=card.querySelector('em');if(!role||!status)return;status.dataset.original??=status.textContent;status.textContent=autoActive?(grouped.has(role)?'Candidato + rascunho manual':'Candidato · revisar'):grouped.has(role)?'Rascunho no mapa':status.dataset.original});const target=document.querySelector('.target-scope');if(target&&!autoActive){target.querySelector('h2').textContent=entries.length?'Camadas do padrão técnico: rascunhos e pendências.':'Camadas que faltam para reproduzir o mapa.';target.querySelector('p').textContent=entries.length?'Os traçados criados neste navegador são vetores georreferenciados de demonstração, mas ainda não foram validados, comparados com documentos ou incorporados aos entregáveis pré-gerados. O caso público permanece fictício.':'Os traçados e números da foto não são extraídos dela. Este caso público tem apenas limite fictício e cobertura de 2023; os itens abaixo dependem das geometrias originais e da revisão do técnico.'}const note=document.querySelector('.layers .note p');if(note)note.textContent='Há cinco camadas candidatas calculadas automaticamente. APP, ARL, largura do rio e área consolidada exigem documentos e validação técnica; rascunhos manuais não são aprovação.';
 }
 function select(id){if(editingLayer){toast('Salve ou cancele a edição antes de selecionar outro traçado.');return}selectedId=id;render();const layer=layers.get(id);if(layer){layer.bringToFront();map.fitBounds(layer.getBounds(),{padding:[65,65],maxZoom:18,animate:false})}}
 function cancelDraw(){handler?.disable();handler=null;activeRole=null;$('manualCancelDraw').hidden=true;$('manualDraw').disabled=!ready;$('manualHint').textContent='Escolha um tipo e clique em “Desenhar no mapa”.'}
 function startDraw(){if(!ready){toast('Aguarde o mapa carregar.');return}if(editingLayer){toast('Salve a edição atual primeiro.');return}if(entries.length>=100){toast('Limite de 100 traçados nesta demonstração. Baixe o GeoJSON antes de continuar.');return}cancelDraw();$('manualVisible').checked=true;activeRole=$('manualRole').value;const type=TYPES[activeRole];if(!type)return;const options={shapeOptions:{color:type.color,weight:3,dashArray:type.dashArray||null},repeatMode:false};handler=type.geometry==='LineString'?new L.Draw.Polyline(map,options):new L.Draw.Polygon(map,{...options,allowIntersection:false,showArea:false});handler.enable();$('manualCancelDraw').hidden=false;$('manualDraw').disabled=true;$('manualHint').textContent=type.geometry==='LineString'?'Clique no rio para marcar os pontos; dê duplo clique para finalizar.':'Clique nos vértices do polígono; clique no primeiro ponto para finalizar.';showMap(false)}
 map.on(L.Draw.Event.CREATED,event=>{if(!handler||!activeRole)return;const role=activeRole,geometry=event.layer.toGeoJSON().geometry,m=measure(geometry);cancelDraw();if(role==='RIO_ATE_10'?m.lengthKm<=0:m.areaHa<=0){toast('Traçado sem medida válida. Tente novamente.');return}const count=entries.filter(e=>e.role===role).length+1,id=(root.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`);entries.push({id,role,name:`${TYPES[role].label} ${count}`,geometry});selectedId=id;save();render();$('manualHint').textContent=`${TYPES[role].label} criado: ${metricText(entries.at(-1))}. Clique em “Editar vértices” para corrigir.`;toast('Vetor criado e medido. É um rascunho para revisão técnica.');});
 $('manualDraw').onclick=startDraw;$('manualCancelDraw').onclick=cancelDraw;$('manualVisible').onchange=render;$('manualList').onclick=event=>{const button=event.target.closest('[data-manual-id]');if(button)select(button.dataset.manualId)};
 $('manualEdit').onclick=()=>{if(!selectedId)return;const layer=layers.get(selectedId);if(!layer?.editing){toast('Este traçado não admite edição nesta versão.');return}editingLayer=layer;layer.editing.enable();$('manualEdit').hidden=true;$('manualSave').hidden=false;$('manualCancelEdit').hidden=false;$('manualDelete').disabled=true;$('manualHint').textContent='Arraste os vértices no mapa. Depois clique em “Salvar contorno”.';};
 $('manualSave').onclick=()=>{if(!editingLayer||!selectedId)return;const entry=entries.find(e=>e.id===selectedId),geometry=editingLayer.toGeoJSON().geometry,m=measure(geometry);if(!entry||!isValidEntry({...entry,geometry})||(entry.role==='RIO_ATE_10'?m.lengthKm<=0:m.areaHa<=0)){toast('Contorno inválido ou vazio. Corrija os vértices.');return}editingLayer.editing.disable();editingLayer=null;entry.geometry=geometry;save();finishEdit();render();$('manualHint').textContent=`Contorno salvo: ${metricText(entry)}. Área atualizada.`;toast('Traçado salvo e área recalculada no navegador.');};
 function finishEdit(){editingLayer=null;$('manualEdit').hidden=false;$('manualSave').hidden=true;$('manualCancelEdit').hidden=true;$('manualDelete').disabled=false}
 $('manualCancelEdit').onclick=()=>{editingLayer?.editing.disable();finishEdit();render();$('manualHint').textContent='Edição descartada; contorno anterior preservado.'};
 $('manualDelete').onclick=()=>{if(!selectedId||!root.confirm('Excluir este traçado manual?'))return;entries=entries.filter(e=>e.id!==selectedId);selectedId=null;save();render();toast('Traçado excluído deste navegador.');};
 $('manualDownload').onclick=()=>{if(!entries.length)return;const features=entries.map(entry=>{const m=measure(entry.geometry);return{type:'Feature',id:entry.id,geometry:entry.geometry,properties:{nome:entry.name,classe:entry.role,area_ha_estimada:Number(m.areaHa.toFixed(4)),extensao_km_estimada:Number(m.lengthKm.toFixed(4)),situacao:'RASCUNHO · não validado',origem:'desenho manual no GeoOps',observacao:entry.role==='AVN-DESC-APP'?'APP ainda não descontada automaticamente':null}}});const blob=new Blob([JSON.stringify({type:'FeatureCollection',features},null,2)],{type:'application/geo+json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='GeoOps_tracados_manuais_RASCUNHO.geojson';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('GeoJSON baixado. Confira os traçados no QGIS antes de usar.');};
 function setContext({sample,segmented,sourceName}){cancelDraw();if(editingLayer){editingLayer.editing.disable();finishEdit()}const nextId=sample?'botucatu':`arquivo:${sourceName||''}`,nextKey=sample?'geoops-manual-botucatu-v1':null;if(nextId!==contextId){contextId=nextId;storageKey=nextKey;entries=load();selectedId=null}hasCoverage=Boolean(sample&&segmented);ready=true;$('manualDraw').disabled=false;render()}
 function open(){showMap(true);$('manualRole').focus({preventScroll:true});$('manualWorkspace').scrollIntoView({block:'nearest',behavior:'smooth'})}
 $('openManual').onclick=open;$('presentationDraw').onclick=open;
 const steps=document.querySelectorAll('.engine-steps>div');if(steps[3])steps[3].querySelector('p').textContent='No link público, a cobertura pré-processada permite reclassificar sem alterar o contorno original. O editor manual cria outros vetores e permite ajustar seus vértices; as medidas são estimativas do navegador.';if(steps[4]){steps[4].querySelector('p').textContent='APP, ARL, rio, AVN-DESC-APP e área consolidada podem ser traçados manualmente como rascunhos. A delimitação e a validação legal automáticas ainda não foram implementadas.';steps[4].querySelector('small').textContent='EDITOR MANUAL · SEM VALIDAÇÃO'}
 $('manualDraw').disabled=true;render();return{setContext,open,measure,setVisible:visible=>{$('manualVisible').checked=Boolean(visible);render()},get visible(){return $('manualVisible').checked},bringToFront:()=>group.eachLayer(layer=>layer.bringToFront()),get count(){return entries.length}}
}
root.GeoOpsManual={init,measure,TYPES};
})(globalThis);
