/* Local GIS workbench. All authoritative areas and exports come from PyQGIS. */
(() => {'use strict';
const $=id=>document.getElementById(id), fmt=(n,d=2)=>Number(n).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const palette={'Talhão de inventário':'#86b07b','Vegetação (revisão)':'#488f60','Área aberta (revisão)':'#d6b756','Água (revisão)':'#5bafce','Grupo espectral A':'#94bd8c','Grupo espectral B':'#c6b579','Grupo espectral C':'#748ca2'};
Object.assign(palette,{'Área de estudo':'#e9e0ad','Vegetação nativa mapeada':'#1f8d49','Uso agropecuário':'#dac372','Água mapeada':'#419dce','Silvicultura mapeada':'#916b44','Outras coberturas':'#aaa0a0'});
const hiddenClasses=new Set();
const sampleContext={project:'Botucatu/SP · estudo demonstrativo',source:'Botucatu/SP · dados públicos',detail:'Copernicus Sentinel-2 RGB · MapBiomas Coleção 9 / cobertura 2023',date:'11 set 2023 · Sentinel-2'};
const publicMode=Boolean(window.GeoOpsPublic?.enabled);
if(!publicMode)$('engineModeNotice').textContent='Na instalação local, as operações podem rodar no PyQGIS desta máquina quando o motor está conectado. O caso público abaixo continua sendo apenas uma base de teste, não o fluxo homologado do cliente.';
const presentationUrl=new URL('index.html',location.href);presentationUrl.search=publicMode?'?demo=public&present=1':'?present=1';$('presentMap').href=presentationUrl.href;$('presentationCTA').href=presentationUrl.href;
let token='',connected=false,busy=false,result=null,selected=null,editing=false,uploadId=null,sourceName='',raster=null,references=null,polygons=null,history=[],exportResult=null,toastTimer;
let sample=true,segmented=false;
const embedded=window.parent!==window&&new URLSearchParams(location.search).get('embedded')==='1';
function tellShell(message){if(embedded)window.parent.postMessage(message,location.origin);}
const map=L.map('gisMap',{zoomControl:false,attributionControl:true,minZoom:2,maxZoom:22,zoomSnap:.25}).setView([-22.984,-48.46],13);
L.control.zoom({position:'bottomright'}).addTo(map);
L.control.scale({imperial:false,position:'bottomleft',maxWidth:130}).addTo(map);
new ResizeObserver(entries=>{if(entries[0].contentRect.width&&entries[0].contentRect.height)map.invalidateSize({pan:true,animate:false});}).observe($('gisMap'));
const publicAttribution='Copernicus Sentinel-2 (2023) · MapBiomas Brasil C9 (2023) · limite fictício';
map.attributionControl.addAttribution(publicAttribution);
map.on('mousemove',e=>{$('coords').textContent=e.latlng.lat.toFixed(5)+'° · '+e.latlng.lng.toFixed(5)+'°'});
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),6500)}
function activeTab(){return document.querySelector('.tabs [data-tab].active')?.dataset.tab||'map'}
function tab(name){document.querySelectorAll('[data-tab]').forEach(b=>{const active=b.dataset.tab===name;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id==='tab-'+name));if(name==='map')requestAnimationFrame(()=>map.invalidateSize({pan:false}));if(publicMode&&name==='exports'&&result&&!exportResult&&!busy)queueMicrotask(()=>{if(!exportResult&&!busy&&activeTab()==='exports')exportAll()});tellShell({type:'geoops:workspace-tab-changed',tab:name});}
function setBusy(value,title='Executando no QGIS'){busy=value;$('jobPanel').hidden=!value;$('jobTitle').textContent=title;$('runTime').textContent=value?title+'…':result?(publicMode?'Resultado público pré-processado':`Última execução: ${fmt(result.elapsedSeconds)} s · medida local`):'Nenhuma execução ainda';$('runTime').classList.toggle('running',value);['loadSample','uploadInput'].forEach(id=>$(id).disabled=value||(publicMode&&id==='uploadInput'));['selectFirst','exportAll','regenerate'].forEach(id=>$(id).disabled=value||!result||(!publicMode&&sample&&!segmented)||(publicMode&&id==='regenerate'));$('fitMap').disabled=value||!result;$('fillOpacity').disabled=value||!result||(sample&&!segmented);$('runClassify').disabled=value||!sample||!result;document.querySelectorAll('#featureForm button,#featureForm select').forEach(b=>b.disabled=value||(publicMode&&b.id==='editGeometry'));}
async function api(path,body){if(publicMode)throw Error('A demonstração pública não conecta ao motor local.');const response=await fetch(path,{method:body?'POST':'GET',headers:{...(token?{'X-GeoOps-Token':token}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Error(data.error||'Não foi possível executar a operação.');return data}
function addHistory(title,detail){history.unshift({title,detail,time:new Date().toLocaleTimeString('pt-BR')});$('historyList').innerHTML=history.map(e=>`<li><b>${esc(e.title)}</b><small>${esc(e.time)} · ${esc(e.detail)}</small></li>`).join('')}
function requestMeta(){return{project:sample?sampleContext.project:sourceName.replace(/\.[^.]+$/,''),client:sample?'Demonstração · limite fictício':'Validação do aplicativo',city:sample?'Botucatu/SP, Brasil':'Localidade do arquivo importado',date:sample?'2023-09-11':'',...(uploadId?{uploadId}:{dataset:'brazil-botucatu'})}}
async function run(operation,extra={},title){if(busy)return;if(publicMode){setBusy(true,title);$('jobDetail').textContent=operation==='revise'?'Atualizando a classificação no navegador; contornos e áreas originais permanecem.':'Carregando dados estáticos pré-processados; não há conexão com o ambiente local.';try{const data=await window.GeoOpsPublic.execute(operation,extra);addHistory(title||operation,operation==='revise'?'Revisão de classes feita neste navegador.':'Resultado pré-processado carregado.');return data;}finally{setBusy(false)}}setBusy(true,title);const started=performance.now();const timer=setInterval(()=>{$('jobElapsed').textContent=Math.floor((performance.now()-started)/1000)+' s'},500);$('jobElapsed').textContent='0 s';try{const job=await api('/api/jobs',{operation,...requestMeta(),...extra});let state;for(;;){await new Promise(r=>setTimeout(r,650));state=await api('/api/jobs/'+job.id);if(state.status==='complete')break;if(state.status==='failed')throw Error(state.error);if(state.status==='missing')throw Error('Execução não localizada. Recarregue o aplicativo.');if(performance.now()-started>270000)throw Error('A execução excedeu o tempo esperado. Consulte o registro local antes de tentar novamente.');$('jobDetail').textContent=state.status==='queued'?'Na fila do motor local.':'Processamento real em execução. Aguardando o retorno do QGIS.';}addHistory(title||operation,`${state.result.summary?.count||0} feições · ${fmt(state.result.elapsedSeconds)} s · arquivos salvos localmente`);return state.result;}finally{clearInterval(timer);setBusy(false)}}
function features(){return [...(result?.features?.features||[])].sort((a,b)=>b.properties.area_ha-a.properties.area_ha)}
function syncVisibility(){if(raster){if($('showRaster').checked&&!map.hasLayer(raster))raster.addTo(map);if(!$('showRaster').checked&&map.hasLayer(raster))map.removeLayer(raster)}if(polygons){if($('showPolygons').checked&&!map.hasLayer(polygons))polygons.addTo(map);if(!$('showPolygons').checked&&map.hasLayer(polygons))map.removeLayer(polygons)}if(references){if($('showReference').checked&&!map.hasLayer(references))references.addTo(map);if(!$('showReference').checked&&map.hasLayer(references))map.removeLayer(references)}$('viewImage').classList.toggle('active',!$('showPolygons').checked);$('viewVectors').classList.toggle('active',$('showPolygons').checked)}
function style(feature){const chosen=String(feature.id??feature.properties.id)===selected,label=feature.properties.class;const illustrated=sample&&segmented;const pattern=illustrated?({'Vegetação nativa mapeada':'url(#geoops-native-dots)','Uso agropecuário':'url(#geoops-agro-hatch)','Vegetação (revisão)':'url(#geoops-native-dots)','Área aberta (revisão)':'url(#geoops-agro-hatch)'}[label]):null;return{color:chosen?'#ffe19a':(palette[label]||'#819578'),weight:chosen?3:1,opacity:.95,fillColor:pattern||palette[label]||'#94ad86',fillOpacity:Number($('fillOpacity').value)/100}}
function installPatterns(){const svg=$('gisMap').querySelector('.leaflet-overlay-pane svg');if(!svg||svg.querySelector('#geoops-technical-patterns'))return;const defs=document.createElementNS('http://www.w3.org/2000/svg','defs');defs.id='geoops-technical-patterns';defs.innerHTML='<pattern id="geoops-native-dots" patternUnits="userSpaceOnUse" width="9" height="9"><circle cx="4.5" cy="4.5" r="1.7" fill="#49bf59"/></pattern><pattern id="geoops-agro-hatch" patternUnits="userSpaceOnUse" width="9" height="9" patternTransform="rotate(35)"><path d="M 0 0 L 0 9" stroke="#ffe36a" stroke-width="2"/></pattern>';svg.prepend(defs)}
function drawVectors(){if(polygons)map.removeLayer(polygons);const displayed=structuredClone(result.features);displayed.features.forEach(f=>{if(f.geometry.type==='MultiPolygon'&&f.geometry.coordinates.length===1)f.geometry={type:'Polygon',coordinates:f.geometry.coordinates[0]}});polygons=L.geoJSON(displayed,{filter:f=>!hiddenClasses.has(f.properties.class),style,onEachFeature:(feature,layer)=>{layer.bindTooltip(esc(feature.properties.name)+' · '+fmt(feature.properties.area_ha)+' ha',{sticky:true});layer.on('click',()=>select(String(feature.id??feature.properties.id)));}});syncVisibility();installPatterns();references?.bringToFront();}
function showResult(data,{fit=false,base=false}={}){invalidateExport();datasetNotice();hiddenClasses.clear();result=data;selected=null;editing=false;$('featureForm').hidden=true;$('presentationSelection').hidden=true;$('selectionEmpty').hidden=false;$('emptyMap').hidden=true;
 if(base){$('showPolygons').checked=!sample;$('showReference').checked=true;}else if(segmented){$('showPolygons').checked=true;$('showReference').checked=true;}
 if(base){if(raster)map.removeLayer(raster);if(references)map.removeLayer(references);raster=null;references=null;const info=data.base;if(info?.file&&info.bounds){const url=data.downloads?.[info.file];if(url)raster=L.imageOverlay(url,info.bounds,{opacity:1,interactive:false});}if(data.boundary)references=L.geoJSON(data.boundary,{interactive:false,style:{color:sample?'#e23d3a':'#fff2b5',weight:sample?3:2.5,fill:false}});map.attributionControl.removeAttribution(publicAttribution);if(sample)map.attributionControl.addAttribution(publicAttribution);}
 $('mapLegend').hidden=!(sample&&segmented);
 drawVectors();if(fit&&data.bounds)map.fitBounds(data.bounds,{padding:[34,34]});const crs=data.crs||{};$('crsLabel').textContent=crs.measurement_crs||crs.source_crs||'Não definido';$('engineBadge').textContent=publicMode?'DEMONSTRAÇÃO PÚBLICA · dados estáticos':'QGIS · motor local ativo';$('engineBadge').classList.toggle('offline',false);$('runTime').textContent=publicMode?'Resultado público pré-processado':`Última execução: ${fmt(data.elapsedSeconds)} s · medida local`;$('totalArea').parentElement.querySelector('span').textContent=publicMode&&!segmented?'ÁREA DE ESTUDO':'ÁREA DAS FEIÇÕES';$('totalArea').innerHTML=fmt(data.summary.totalHa)+'<small>ha</small>';$('areaMethod').textContent=publicMode&&!segmented?'Perímetro fictício do caso-base. Clique em Cobertura do solo para mostrar as classes.':publicMode?'Áreas originais calculadas no caso-base; reclassificar não cria nova medição.':`Área projetada em ${crs.measurement_crs}. Soma das feições; sobreposições são indicadas no QA.`;$('layerCount').textContent=(raster?1:0)+(references?1:0)+(segmented||!sample?1:0);$('featureCount').textContent=data.summary.count;$('mapStatus').textContent=publicMode?(segmented?`${data.summary.count} feições pré-processadas · ${crs.measurement_crs}`:'Imagem e limite de estudo pré-processados'):`${data.summary.count} feições · ${crs.measurement_crs} · fonte ${sample?'pública':'importada'}`;const reviewed=features().filter(f=>f.properties.reviewed).length;$('reviewedCount').textContent=reviewed;$('reviewBadge').textContent=reviewed?'REVISÃO PARCIAL':'PENDENTE';$('stepData').classList.add('done');$('stepReview').classList.toggle('done',reviewed>0);$('stepVectors').classList.toggle('done',segmented);
 const groups=new Map();for(const f of features()){let p=f.properties;groups.set(p.class,(groups.get(p.class)||0)+p.area_ha)}
 $('presentationTitle').textContent=sample?'Botucatu/SP · cobertura do solo 2023':sourceName||'Camada importada · revisão técnica';
 $('presentationAreas').innerHTML=[...groups].sort((a,b)=>b[1]-a[1]).slice(0,6).map(([label,value])=>`<tr><td>${esc(label)}</td><td>${fmt(value)}</td><td>${fmt(data.summary.totalHa?value/data.summary.totalHa*100:0)}%</td></tr>`).join('')+`<tr><td>Total das feições</td><td>${fmt(data.summary.totalHa)}</td><td>100%</td></tr>`;
 $('classSummary').innerHTML=sample&&!segmented?(publicMode?'<p class="subtle">Clique em <b>Cobertura do solo</b> ou <b>Mostrar cobertura</b> para ver as classes pré-processadas.</p>':'<p class="subtle">Clique em <b>Processar cobertura</b> para recortar e vetorizar as classes MapBiomas.</p>'):[...groups].map(([label,value])=>{const symbol=sample&&segmented?({'Vegetação nativa mapeada':'native-dots','Uso agropecuário':'agro-hatch'}[label]):null;return `<button type="button" class="class-row" data-class="${esc(label)}" aria-pressed="true" title="Mostrar/ocultar ${esc(label)}"><i class="swatch ${symbol||''}" ${symbol?'':`style="background:${palette[label]||'#94ad86'}"`}></i><span>${esc(label)}<small>${fmt(data.summary.totalHa?value/data.summary.totalHa*100:0)}%</small></span><strong>${fmt(value)}</strong></button>`}).join('');
 $('attributesBody').innerHTML=features().map(f=>`<tr data-id="${esc(f.id??f.properties.id)}"><td><button>${esc(f.properties.name)}</button></td><td>${esc(f.properties.class)}</td><td>${fmt(f.properties.area_ha,4)}</td><td>${fmt(f.properties.pct)}%</td><td>${f.properties.reviewed?'Revisada':'Pendente'}</td></tr>`).join('');
 $('qaList').innerHTML=(data.qa||[]).map(q=>`<div class="qa-item ${q.status==='ok'?'':'warn'}"><i>${q.status==='ok'?'✓':'!'}</i><div><strong>${esc(q.name)}</strong><p>${esc(q.detail)}</p></div></div>`).join('');
 $('caseReading').textContent=sample&&segmented?`No limite fictício de ${fmt(data.summary.totalHa)} ha, a revisão atual contém ${fmt(groups.get('Vegetação nativa mapeada')||0)} ha na classe “vegetação nativa mapeada” e ${fmt(groups.get('Uso agropecuário')||0)} ha de uso agropecuário. Isso ajuda a organizar a análise. Não informa, sozinho, quantos hectares precisam ser recuperados ou se o imóvel está regular.`:sample?'Primeiro você vê a imagem real e o limite fictício de estudo. Clique em Processar cobertura para ver os hectares mapeados.':'Você está analisando um arquivo importado. A origem e a finalidade das feições precisam ser conferidas; não é o caso demonstrativo de Botucatu.';
 setBusy(false);
}
function select(id){if(busy)return;if(editing){toast('Salve ou cancele a edição atual antes de selecionar outra feição.');return}selected=id;const feature=features().find(f=>String(f.id??f.properties.id)===id);if(!feature)return;$('showPolygons').checked=true;syncVisibility();polygons.setStyle(style);polygons.eachLayer(l=>{if(String(l.feature.id??l.feature.properties.id)===id)l.bringToFront()});$('presentationSelection').hidden=false;$('presentationSelectionName').textContent=feature.properties.name;$('presentationSelectionClass').textContent=feature.properties.class;$('presentationSelectionArea').textContent=fmt(feature.properties.area_ha,4)+' ha';$('selectionEmpty').hidden=true;$('featureForm').hidden=false;$('featureCode').textContent='FEIÇÃO '+id;$('featureName').textContent=feature.properties.name;$('featureArea').textContent=fmt(feature.properties.area_ha,4)+' ha';const select=$('featureClass');for(const option of [...select.options])if(option.dataset.spectral)option.remove();if(![...select.options].some(o=>o.value===feature.properties.class)){const option=new Option(feature.properties.class,feature.properties.class);option.dataset.spectral='true';select.add(option)}select.value=feature.properties.class;$('editHint').textContent=publicMode?'No modo público, apenas classe e marca de revisão podem mudar. A área e o contorno originais são preservados.':'A classe original permanece até você confirmar.';$('editGeometry').textContent='✎ Editar contorno no mapa';const editable=!publicMode&&(feature.geometry.type==='Polygon'||(feature.geometry.type==='MultiPolygon'&&feature.geometry.coordinates.length===1));$('editGeometry').disabled=!editable;if(publicMode)$('editGeometry').textContent='Contorno bloqueado nesta demonstração';else if(!editable)$('editHint').textContent='Feição multipartes: classe revisável; edição de contorno desta versão aceita polígonos simples.';document.querySelectorAll('#attributesBody tr').forEach(tr=>tr.classList.toggle('selected',tr.dataset.id===id));}
function layerForSelected(){let found;polygons?.eachLayer(l=>{if(String(l.feature.id??l.feature.properties.id)===selected)found=l});return found}
function invalidateExport(){exportResult=null;$('stepExport').classList.remove('done');$('exportVersion').textContent='Gere a entrega desta revisão';$('downloadList').replaceChildren();$('mapPreview').hidden=true;$('previewEmpty').hidden=false;}
function datasetNotice(){ $('datasetNotice').textContent=publicMode?'Exemplo fixo de Botucatu/SP. Este link não busca imagens de outros lugares, não envia arquivos e não mede novamente a área.':sample?'Imagem e cobertura reais. Limite fictício de estudo, não uma fazenda cadastrada.':'Arquivo importado pelo usuário. Classes ambientais, finalidade da camada e enquadramento precisam de confirmação técnica.'; }
function restoreContext(previous){({sample,uploadId,sourceName,segmented}=previous);$('projectTitle').textContent=sample?sampleContext.project:sourceName;$('sourceTitle').textContent=sample?sampleContext.source:'Arquivo importado · '+sourceName;$('sourceDetail').textContent=sample?sampleContext.detail:'Processamento nesta máquina · arquivo original preservado';$('imageDate').textContent=sample?sampleContext.date:'Não fornecida';$('polygonLabel').innerHTML=segmented?'Cobertura vetorizada<small>MapBiomas 2023 · revisar</small>':sample?(publicMode?'Cobertura do solo<small>Clique para mostrar os vetores</small>':'Cobertura do solo<small>Disponível após processar</small>'):'Feições do arquivo<small>Sem classificação inferida</small>';datasetNotice();setBusy(false);}
function reviewRequest(){return{features:structuredClone(result.features),source_crs:result.crs.measurement_crs||result.crs.source_crs,reviewed:features().filter(f=>f.properties.reviewed).map(f=>String(f.id??f.properties.id))}}
async function loadSample(){const previous={sample,uploadId,sourceName,segmented};try{restoreContext({sample:true,uploadId:null,sourceName:'',segmented:false});$('stepExport').classList.remove('done');tab('map');const data=await run('prepare',{},publicMode?'Carregando imagem e limite do caso público':'Abrindo imagem pública e limite de estudo de Botucatu');if(data)showResult(data,{fit:true,base:true});}catch(e){restoreContext(previous);toast(e.message)}}
async function connect(){if(publicMode){connected=true;window.GeoOpsPublic.setup();$('connectionError').hidden=true;$('loadSample').disabled=false;if(!result)await loadSample();return}try{const cfg=await api('/api/config');token=cfg.token;connected=cfg.engineAvailable;$('connectionError').hidden=connected;$('engineBadge').textContent=connected?'QGIS · ambiente local':'Motor indisponível';$('engineBadge').classList.toggle('offline',!connected);$('loadSample').disabled=!connected;if(connected&&!result)await loadSample();}catch(e){connected=false;$('connectionError').hidden=false;$('engineBadge').textContent='Motor local desconectado';$('engineBadge').classList.add('offline');$('loadSample').disabled=true;}}
$('loadSample').onclick=loadSample;$('retryConnection').onclick=connect;$('showEngine').onclick=()=>tab('engine');$('showScope').onclick=()=>tab('qa');$('engineViewMap').onclick=()=>tab('map');$('engineViewQa').onclick=()=>tab('qa');$('showTarget').onclick=()=>$('targetDialog').showModal();$('mapLegendDetails').onclick=()=>$('targetDialog').showModal();document.querySelector('#targetDialog .close').onclick=()=>$('targetDialog').close();
function enterPresentation(){if(!result)return;document.body.classList.add('map-presentation');$('presentationChrome').hidden=false;$('showPolygons').checked=segmented||!sample;syncVisibility();requestAnimationFrame(()=>{map.invalidateSize({pan:false});if(result.bounds)map.fitBounds(result.bounds,{padding:[100,105],animate:false})});}
function exitPresentation(){document.body.classList.remove('map-presentation','presentation-layers-open');$('presentationChrome').hidden=true;requestAnimationFrame(()=>map.invalidateSize({pan:false}));}
$('presentationLayers').onclick=()=>document.body.classList.toggle('presentation-layers-open');$('presentationExit').onclick=exitPresentation;document.addEventListener('keydown',event=>{if(event.key==='Escape'&&document.body.classList.contains('map-presentation'))exitPresentation()});
$('presentationReview').onclick=()=>{exitPresentation();tab('map');requestAnimationFrame(()=>$('featureForm').scrollIntoView({behavior:'smooth',block:'center'}))};
$('runClassify').onclick=async()=>{const startedFrom=activeTab();try{if(!sample||!result||busy)return;if(publicMode&&segmented){$('showPolygons').checked=true;$('showReference').checked=true;syncVisibility();tab('map');toast('A cobertura já está no mapa. Clique numa feição para revisar a classe.');return}const data=await run('classify',{},publicMode?'Exibindo cobertura pré-processada':'Recortando e vetorizando a cobertura MapBiomas 2023');if(data){segmented=true;$('polygonLabel').innerHTML='Cobertura vetorizada<small>MapBiomas 2023 · revisar</small>';showResult(data,{fit:true});if(activeTab()===startedFrom)tab('map');toast(publicMode?'Cobertura pré-processada exibida. Clique numa feição para revisar; contornos e áreas não mudam nesta demonstração.':'Cobertura pública convertida em vetores. Classes e limites exigem revisão técnica.');}}catch(e){$('showPolygons').checked=false;syncVisibility();toast(e.message)}};
$('uploadInput').onchange=async e=>{const file=e.target.files[0];if(!file||busy)return;if(file.size>24*1024*1024){toast('Limite de 24 MB. Use um recorte da sua área de trabalho.');return}const previous={sample,uploadId,sourceName,segmented};try{setBusy(true,'Importando arquivo local');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));const uploaded=await api('/api/upload',{name:file.name,content:btoa(binary)});setBusy(false);sample=false;segmented=false;uploadId=uploaded.uploadId;sourceName=file.name;const data=await run('prepare',{},'Validando a camada importada');if(data){$('projectTitle').textContent=file.name;$('sourceTitle').textContent='Arquivo importado · '+file.name;$('sourceDetail').textContent='Processamento nesta máquina · arquivo original preservado';$('imageDate').textContent='Não fornecida';$('polygonLabel').innerHTML='Feições do arquivo<small>Sem classificação inferida</small>';showResult(data,{fit:true,base:true});tab('map');toast('Camada importada e calculada. Sugestão por imagem disponível apenas na base pública desta versão.');}}catch(err){restoreContext(previous);toast(err.message)}finally{setBusy(false);e.target.value=''}};
$('featureForm').onsubmit=async e=>{e.preventDefault();if(!selected||busy)return;const request=reviewRequest();const f=request.features.features.find(f=>String(f.id??f.properties.id)===selected);f.properties.class=$('featureClass').value;f.properties.reviewed=true;if(editing)f.geometry=layerForSelected().toGeoJSON().geometry;if(!request.reviewed.includes(selected))request.reviewed.push(selected);try{const data=await run('revise',request,publicMode?'Salvando revisão de classes no navegador':'Validando a revisão e recalculando hectares');if(data){showResult(data);invalidateExport();toast(publicMode?'Revisão salva neste navegador. Áreas e contornos do caso-base foram preservados.':'Revisão salva. Áreas recalculadas pelo QGIS.');}}catch(err){toast(err.message)}};
$('editGeometry').onclick=()=>{const layer=layerForSelected();if(!layer?.editing)return;editing=true;map.fitBounds(layer.getBounds(),{padding:[80,80],maxZoom:19,animate:false});layer.editing.enable();$('editGeometry').disabled=true;$('editHint').textContent='Arraste os pontos do contorno. Salvar envia a nova geometria ao QGIS; cancelar descarta esta edição.';};
$('cancelEdit').onclick=()=>{selected=null;editing=false;drawVectors();$('featureForm').hidden=true;$('selectionEmpty').hidden=false;};
$('selectFirst').onclick=()=>{if(features().length)select(String(features()[0].id??features()[0].properties.id))};
$('attributesBody').onclick=e=>{const row=e.target.closest('tr[data-id]');if(row){select(row.dataset.id);const layer=layerForSelected();if(layer)map.fitBounds(layer.getBounds(),{padding:[75,75],maxZoom:18})}};
async function exportAll(){if(!result||busy)return;if(editing){toast('Salve ou cancele a edição de contorno antes de gerar a entrega.');return}const startedFrom=activeTab();try{const data=await run('export',reviewRequest(),publicMode?'Abrindo arquivos pré-gerados do caso-base':'Gerando mapa, projeto QGIS e arquivos de entrega');if(!data)return;exportResult=data;$('stepExport').classList.add('done');$('exportVersion').textContent=publicMode?'Caso-base pré-gerado':'Exportação atual · '+new Date().toLocaleTimeString('pt-BR');const files=data.downloads||{};const names=[['mapa.pdf','Baixar mapa PDF','A3 · QGIS'],['GeoOps_Projeto_Completo.zip','Baixar projeto completo','ZIP'],['projeto.gpkg','GeoPackage','GPKG'],['shapefile.zip','Shapefile','ZIP'],['vetores.geojson',publicMode?'Vetores do caso-base':'Vetores revisados','GeoJSON']];$('downloadList').innerHTML=names.filter(([name])=>files[name]).map(([name,label,type])=>`<a href="${files[name]}" download>${label}<span>${type} ↓</span></a>`).join('');const preview=files['mapa.png'];if(preview){$('mapPreview').src=preview;$('mapPreview').hidden=false;$('previewEmpty').hidden=true}window.GeoOpsPublic?.renderLabels(result);if(activeTab()===startedFrom)tab('exports');toast(publicMode?'Arquivos pré-gerados do caso-base disponíveis. Revisões podem ser baixadas separadamente em GeoJSON.':'Arquivos gerados pelo QGIS. O ZIP reúne o projeto e suas camadas.');}catch(e){toast(e.message)}}
$('exportAll').onclick=exportAll;$('regenerate').onclick=exportAll;$('fitMap').onclick=()=>{if(result?.bounds)map.fitBounds(result.bounds,{padding:[34,34]})};
['showRaster','showReference'].forEach(id=>$(id).onchange=syncVisibility);$('showPolygons').onchange=async()=>{if(publicMode&&!segmented&&$('showPolygons').checked){await $('runClassify').onclick();return}syncVisibility()};$('fillOpacity').oninput=()=>{$('fillValue').textContent=$('fillOpacity').value+'%';polygons?.setStyle(style)};$('viewImage').onclick=()=>{$('showPolygons').checked=false;$('showReference').checked=true;syncVisibility()};$('viewVectors').onclick=async()=>{if(publicMode&&!segmented){await $('runClassify').onclick();return}$('showPolygons').checked=true;$('showReference').checked=true;syncVisibility()};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('showMethod').onclick=()=>$('methodDialog').showModal();document.querySelector('#methodDialog .close').onclick=()=>$('methodDialog').close();
$('explainCase').onclick=()=>$('caseDialog').showModal();$('closeCase').onclick=()=>$('caseDialog').close();$('viewCaseMap').onclick=()=>$('caseDialog').close();
$('featureClass').replaceChildren(...['Vegetação nativa mapeada','Uso agropecuário','Água mapeada','Silvicultura mapeada','Outras coberturas','Vegetação (revisão)','Área aberta (revisão)','Água (revisão)'].map(label=>new Option(label,label)));
$('classSummary').onclick=e=>{const button=e.target.closest('[data-class]');if(!button||busy)return;if(editing){toast('Salve ou cancele o contorno antes de mudar as camadas.');return}const label=button.dataset.class;if(hiddenClasses.has(label))hiddenClasses.delete(label);else hiddenClasses.add(label);button.setAttribute('aria-pressed',String(!hiddenClasses.has(label)));button.classList.toggle('muted',hiddenClasses.has(label));$('showPolygons').checked=true;drawVectors();};
if(embedded){
 new ResizeObserver(()=>{const height=document.querySelector('main').getBoundingClientRect().height;if(height>0)tellShell({type:'geoops:workspace-size',height:Math.ceil(height+20)});}).observe(document.querySelector('main'));
 window.addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==window.parent)return;if(event.data?.type==='geoops:workspace-tab'&&['map','qa','exports'].includes(event.data.tab))tab(event.data.tab);});
}
connect().then(async()=>{if(new URLSearchParams(location.search).get('present')!=='1'||!result)return;if(sample&&!segmented)await $('runClassify').onclick();if(result)enterPresentation();}).finally(()=>tellShell({type:'geoops:workspace-ready'}));
})();
